{{
    config(
        alias="apa",
        schema= "brutos_gdb_sia",
        partition_by={
            "field": "data_particao",
            "data_type": "date",
            "granularity": "month",
        },
    )
}}

with source as (
    select * from {{ source('brutos_gdb_sia_staging', 'TB_APA') }}
),
extracted as (
    select

        json_extract_scalar(json, "$.APA_GESTOR") as APA_GESTOR,
        json_extract_scalar(json, "$.APA_CONDIC") as APA_CONDIC,
        json_extract_scalar(json, "$.APA_UID") as APA_UID,
        json_extract_scalar(json, "$.APA_NUM") as APA_NUM,
        json_extract_scalar(json, "$.APA_EMISSA") as APA_EMISSA,
        json_extract_scalar(json, "$.APA_DTINIC") as APA_DTINIC,
        json_extract_scalar(json, "$.APA_DTFIM") as APA_DTFIM,
        json_extract_scalar(json, "$.APA_TPATEN") as APA_TPATEN,
        json_extract_scalar(json, "$.APA_TPAPAC") as APA_TPAPAC,
        json_extract_scalar(json, "$.APA_NMPCN") as APA_NMPCN,
        json_extract_scalar(json, "$.APA_UFPCN") as APA_UFPCN,
        json_extract_scalar(json, "$.APA_MAEPCN") as APA_MAEPCN,
        json_extract_scalar(json, "$.APA_LOGPCN") as APA_LOGPCN,
        json_extract_scalar(json, "$.APA_NUMPCN") as APA_NUMPCN,
        json_extract_scalar(json, "$.APA_CPLPCN") as APA_CPLPCN,
        json_extract_scalar(json, "$.APA_CEPPCN") as APA_CEPPCN,
        json_extract_scalar(json, "$.APA_MUNPCN") as APA_MUNPCN,
        json_extract_scalar(json, "$.APA_DTNASC") as APA_DTNASC,
        json_extract_scalar(json, "$.APA_SEXPCN") as APA_SEXPCN,
        json_extract_scalar(json, "$.APA_VARIA") as APA_VARIA,
        json_extract_scalar(json, "$.APA_CPFRES") as APA_CPFRES,
        json_extract_scalar(json, "$.APA_NMRES") as APA_NMRES,
        json_extract_scalar(json, "$.APA_MOTCOB") as APA_MOTCOB,
        json_extract_scalar(json, "$.APA_DTOBAL") as APA_DTOBAL,
        json_extract_scalar(json, "$.APA_CPFDIR") as APA_CPFDIR,
        json_extract_scalar(json, "$.APA_NMDIR") as APA_NMDIR,
        json_extract_scalar(json, "$.APA_CMP") as APA_CMP,
        json_extract_scalar(json, "$.APA_MVM") as APA_MVM,
        json_extract_scalar(json, "$.APA_RMS") as APA_RMS,
        json_extract_scalar(json, "$.APA_DTGER") as APA_DTGER,
        json_extract_scalar(json, "$.APA_FLER") as APA_FLER,
        json_extract_scalar(json, "$.APA_INERPP") as APA_INERPP,
        json_extract_scalar(json, "$.APA_PRIPAL") as APA_PRIPAL,
        json_extract_scalar(json, "$.APA_SMTRD") as APA_SMTRD,
        json_extract_scalar(json, "$.APA_CNSPCT") as APA_CNSPCT,
        json_extract_scalar(json, "$.APA_CPFPCT") as APA_CPFPCT,
        json_extract_scalar(json, "$.APA_CNSRES") as APA_CNSRES,
        json_extract_scalar(json, "$.APA_CNSDIR") as APA_CNSDIR,
        json_extract_scalar(json, "$.APA_CIDCA") as APA_CIDCA,
        json_extract_scalar(json, "$.APA_NPRONT") as APA_NPRONT,
        json_extract_scalar(json, "$.APA_CODSOL") as APA_CODSOL,
        json_extract_scalar(json, "$.APA_DTSOL") as APA_DTSOL,
        json_extract_scalar(json, "$.APA_DTAUT") as APA_DTAUT,
        json_extract_scalar(json, "$.APA_CODEMI") as APA_CODEMI,
        json_extract_scalar(json, "$.APA_CATEND") as APA_CATEND,
        json_extract_scalar(json, "$.APA_APACAN") as APA_APACAN,
        json_extract_scalar(json, "$.APA_RACA") as APA_RACA,
        json_extract_scalar(json, "$.APA_NOMERE") as APA_NOMERE,
        json_extract_scalar(json, "$.APA_ETNIA") as APA_ETNIA,
        json_extract_scalar(json, "$.APA_ADVLMC") as APA_ADVLMC,
        json_extract_scalar(json, "$.APA_SRV") as APA_SRV,
        json_extract_scalar(json, "$.APA_CSF") as APA_CSF,
        json_extract_scalar(json, "$.APA_ADVTZM") as APA_ADVTZM,
        json_extract_scalar(json, "$.APA_COD_LOGR") as APA_COD_LOGR,
        json_extract_scalar(json, "$.APA_BAIRRO") as APA_BAIRRO,
        json_extract_scalar(json, "$.APA_DDD") as APA_DDD,
        json_extract_scalar(json, "$.APA_TEL") as APA_TEL,
        json_extract_scalar(json, "$.APA_EMAIL") as APA_EMAIL,
        json_extract_scalar(json, "$.APA_CNS_EXE") as APA_CNS_EXE,
        json_extract_scalar(json, "$.APA_INE") as APA_INE,
        json_extract_scalar(json, "$.APA_ADVSEX") as APA_ADVSEX,
        json_extract_scalar(json, "$.APA_STRUA") as APA_STRUA,
        -- json_extract_scalar(json, "$.CHECK_SUM") as CHECK_SUM,

        _source_file,
        _loaded_at,
        data_particao
    from source
),

renamed as (
    select

        cast({{ process_null("APA_GESTOR") }} as string) as gestor,
        cast({{ process_null("APA_CONDIC") }} as string) as condic,
        cast({{ process_null("APA_UID") }} as string) as uid,
        cast({{ process_null("APA_NUM") }} as string) as num,
        cast({{ process_null("APA_EMISSA") }} as string) as emissa,
        cast({{ process_null("APA_DTINIC") }} as string) as data_inicio,
        cast({{ process_null("APA_DTFIM") }} as string) as data_fim,
        cast({{ process_null("APA_TPATEN") }} as string) as tipo_atencao,
        cast({{ process_null("APA_TPAPAC") }} as string) as tipo_apac,
        cast({{ process_null("trim(APA_NMPCN)") }} as string) as paciente_nome,
        cast({{ process_null("APA_UFPCN") }} as string) as paciente_uf,
        cast({{ process_null("trim(APA_MAEPCN)") }} as string) as paciente_mae_nome,
        cast({{ process_null("trim(APA_LOGPCN)") }} as string) as paciente_endereco_logradouro,
        cast({{ process_null("APA_NUMPCN") }} as string) as paciente_endereco_numero,
        cast({{ process_null("APA_CPLPCN") }} as string) as paciente_endereco_complemento,
        cast({{ process_null("APA_CEPPCN") }} as string) as paciente_endereco_cep,
        cast({{ process_null("APA_MUNPCN") }} as string) as paciente_endereco_municipio,
        cast({{ process_null("APA_DTNASC") }} as string) as paciente_data_nascimento,
        cast({{ process_null("APA_SEXPCN") }} as string) as paciente_sexo,
        cast({{ process_null("APA_CNSPCT") }} as string) as paciente_cns,
        cast({{ process_null("APA_CPFPCT") }} as string) as paciente_cpf,
        cast({{ process_null("trim(APA_VARIA)") }} as string) as varia,
        cast({{ process_null("trim(APA_NMRES)") }} as string) as res_nome,
        cast({{ process_null("APA_CPFRES") }} as string) as res_cpf,
        cast({{ process_null("APA_CNSRES") }} as string) as res_cns,
        cast({{ process_null("trim(APA_NMDIR)") }} as string) as dir_nome,
        cast({{ process_null("APA_CPFDIR") }} as string) as dir_cpf,
        cast({{ process_null("APA_CNSDIR") }} as string) as dir_cns,
        cast({{ process_null("APA_MOTCOB") }} as string) as motcob,
        cast({{ process_null("APA_DTOBAL") }} as string) as dtobal,
        case
            when length(trim(APA_CMP)) = 6 and regexp_contains(trim(APA_CMP), r'^[0-9]+$')
                then concat(left(trim(APA_CMP), 4), '-', right(trim(APA_CMP), 2))
            else cast({{ process_null("APA_CMP") }} as string)
        end as mes_competencia,
        cast({{ process_null("APA_MVM") }} as string) as mvm,
        cast({{ process_null("APA_RMS") }} as string) as rms,
        cast({{ process_null("APA_DTGER") }} as string) as data_ger,
        cast({{ process_null("APA_FLER") }} as string) as fler,
        cast({{ process_null("APA_INERPP") }} as string) as inerpp,
        cast({{ process_null("APA_PRIPAL") }} as string) as pripal,
        cast({{ process_null("APA_SMTRD") }} as string) as smtrd,
        cast({{ process_null("trim(APA_CIDCA)") }} as string) as cid_ca,
        cast({{ process_null("trim(APA_NPRONT)") }} as string) as numero_prontuario,
        cast({{ process_null("APA_CODSOL") }} as string) as codigo_solicitacao,
        cast({{ process_null("APA_DTSOL") }} as string) as data_solicitacao,
        cast({{ process_null("APA_DTAUT") }} as string) as data_autorizacao, --?
        cast({{ process_null("APA_CODEMI") }} as string) as codigo_emi,
        cast({{ process_null("APA_CATEND") }} as string) as catend,
        cast({{ process_null("APA_APACAN") }} as string) as apacan,
        cast({{ process_null("APA_RACA") }} as string) as raca,
        cast({{ process_null("trim(APA_NOMERE)") }} as string) as re_nome,
        cast({{ process_null("APA_ETNIA") }} as string) as etnia,
        cast({{ process_null("APA_ADVLMC") }} as string) as advlmc,
        cast({{ process_null("APA_SRV") }} as string) as srv,
        cast({{ process_null("APA_CSF") }} as string) as csf,
        cast({{ process_null("APA_ADVTZM") }} as string) as advtzm,
        cast({{ process_null("APA_COD_LOGR") }} as string) as cod_logr,
        cast({{ process_null("trim(APA_BAIRRO)") }} as string) as bairro,
        cast({{ process_null("APA_DDD") }} as string) as telefone_ddd,
        cast({{ process_null("APA_TEL") }} as string) as telefone_numero,
        cast({{ process_null("trim(APA_EMAIL)") }} as string) as email,
        cast({{ process_null("APA_CNS_EXE") }} as string) as exe_cns,
        cast({{ process_null("APA_INE") }} as string) as ine,
        cast({{ process_null("APA_ADVSEX") }} as string) as advsex,
        cast({{ process_null("APA_STRUA") }} as string) as strua,

        -- Podem ser usados posteriormente para deduplicação
        safe_cast(data_particao as date) as data_particao,
        safe_cast(_loaded_at as timestamp) as data_carga
    from extracted
)
select *
from renamed
