{{
    config(
        alias="idoso", 
        materialized="incremental",
        unique_key = 'id_prontuario_global',
        cluster_by= 'id_prontuario_global',
        schema="brutos_prontuario_vitacare_historico",
        partition_by={
            "field": "data_particao",
            "data_type": "date",
            "granularity": "day"
        }
    )
}}

{% set last_partition = get_last_partition_date(this) %}

with

    source_idoso as (
        select 
            concat(
                nullif(id_cnes, ''), 
                '.',
                nullif(replace(acto_id, '.0', ''), '')
            ) as id_prontuario_global,
            *
        from {{ source('brutos_prontuario_vitacare_historico_staging', 'idoso') }} 
        {% if is_incremental() %}
            where data_particao > '{{last_partition}}'
        {% endif %}
    ),


      -- Using window function to deduplicate idoso
    idoso_deduplicados as (
        select
            *
        from source_idoso 
        qualify row_number() over (partition by id_prontuario_global order by extracted_at desc) = 1 
    ),

    fato_idoso as (
        select
            -- PKs e Chaves
            id_prontuario_global,
            replace(acto_id, '.0', '') as id_prontuario_local,
            id_cnes,

            {{ process_null('depbarthelalimentacao') }} as dep_barthel_alimentacao,
            {{ process_null('depbarthelbanho') }} as dep_barthel_banho,
            {{ process_null('depbarthelhigienepessoal') }} as dep_barthel_higiene_pessoal,
            {{ process_null('depbarthelvestirse') }} as dep_barthel_vestirse,
            {{ process_null('depbarthelcontroloanal') }} as dep_barthel_controlo_anal,
            {{ process_null('depbarthelcontrolovesical') }} as dep_barthel_controlo_vesical,
            {{ process_null('depbarthelutilizacaosanita') }} as dep_barthel_utilizacao_sanita,
            {{ process_null('depbartheltransferencia') }} as dep_barthel_transferencia,
            {{ process_null('depbarthelmobilidade') }} as dep_barthel_mobilidade,
            {{ process_null('depbarthelescadas') }} as dep_barthel_escadas,
            {{ process_null('depbartheltotal') }} as dep_barthel_total,
            {{ process_null('depmmsorientacaoano') }} as dep_mms_orientacao_ano,
            {{ process_null('depmmsorientacaomes') }} as dep_mms_orientacao_mes,
            {{ process_null('depmmsorientacaodiames') }} as dep_mms_orientacao_dia_mes,
            {{ process_null('depmmsorientacaodiaseman') }} as dep_mms_orientacao_dia_seman,
            {{ process_null('depmmslinguagemarelogio') }} as dep_mms_linguagem_arelogio,
            {{ process_null('depmmslinguagemc1') }} as dep_mms_linguagem_c1,
            {{ process_null('depmmslinguagemc2') }} as dep_mms_linguagem_c2,
            {{ process_null('depmmslinguagemc3') }} as dep_mms_linguagem_c3,
            {{ process_null('depmmslinguagemdolhos') }} as dep_mms_linguagem_dolhos,
            {{ process_null('depmmslinguagemefrase') }} as dep_mms_linguagem_efrase,
            {{ process_null('depmmshabilidadedesenho') }} as dep_mms_habilidade_desenho,
            {{ process_null('depmmspontosp') }} as dep_mms_pontos_p,
            {{ process_null('depobservacoes') }} as dep_observacoes,
            {{ process_null('depmmsconclusao') }} as dep_mms_conclusao,
            {{ process_null('depmmsretencaocaneca') }} as dep_mms_retencao_caneca,
            {{ process_null('depmmsretencaotijolo') }} as dep_mms_retencao_tijolo,
            {{ process_null('depmmsretencaotapete') }} as dep_mms_retencao_tapete,
            {{ process_null('depmmsorientacaosemestre') }} as dep_mms_orientacao_semestre,
            {{ process_null('depmmsorientacaoestado') }} as dep_mms_orientacao_estado,
            {{ process_null('depmmsorientacaocidade') }} as dep_mms_orientacao_cidade,
            {{ process_null('depmmsorientacaobairro') }} as dep_mms_orientacao_bairro,
            {{ process_null('depmmsorientacaorua') }} as dep_mms_orientacao_rua,
            {{ process_null('depmmsorientacaolocal') }} as dep_mms_orientacao_local,
            {{ process_null('depmmscalculoaval') }} as dep_mms_calculo_aval,
            {{ process_null('depmmscalculo93') }} as dep_mms_calculo_93,
            {{ process_null('depmmscalculo86') }} as dep_mms_calculo_86,
            {{ process_null('depmmscalculo79') }} as dep_mms_calculo_79,
            {{ process_null('depmmscalculo72') }} as dep_mms_calculo_72,
            {{ process_null('depmmscalculo65') }} as dep_mms_calculo_65,
            {{ process_null('depmmsmemorizacaocaneca') }} as dep_mms_memorizacao_caneca,
            {{ process_null('depmmsmemorizacaotijolo') }} as dep_mms_memorizacao_tijolo,
            {{ process_null('depmmsmemorizacaotapete') }} as dep_mms_memorizacao_tapete,
            {{ process_null('depmmslinguagemacaneca') }} as dep_mms_linguagem_acaneca,
            {{ process_null('depmmslinguagembfrase2') }} as dep_mms_linguagem_bfrase2,
            {{ process_null('depmmsescolaridade2') }} as dep_mms_escolaridade2,
            {{ process_null('depdesenharelogio1') }} as dep_desenhar_elogio1,
            {{ process_null('depdesenharelogio2') }} as dep_desenhar_elogio2,
            {{ process_null('depdesenharelogio3') }} as dep_desenhar_elogio3,
            {{ process_null('idosodepennutricaoperdeupeso') }} as idoso_depen_nutricao_perdeu_peso,
            {{ process_null('idosodependificuldadevisual') }} as idoso_depen_dificuldade_visual,
            {{ process_null('idosodependificuldadevisualolhodir') }} as idoso_depen_dificuldade_visual_olho_dir,
            {{ process_null('idosodependificuldadevisualolhoesq') }} as idoso_depen_dificuldade_visual_olho_esq,
            {{ process_null('idosodepentestesusurro') }} as idoso_depen_teste_sussurro,
            {{ process_null('idosodepencerumeod') }} as idoso_depen_cerume_od,
            {{ process_null('idosodepencerumeoe') }} as idoso_depen_cerume_oe,
            {{ process_null('idosodepenperdeurina') }} as idoso_depen_perde_urina,
            {{ process_null('idosodepenperdeurinaincomodo') }} as idoso_depen_perde_urina_incomodo,
            {{ process_null('idosodepentristefrequente') }} as idoso_depen_triste_frequente,
            {{ process_null('idosodepenrepetirnomesobject') }} as idoso_depen_repetir_nomes_object,
            {{ process_null('idosodepentocarnumcamaos') }} as idoso_depen_tocar_num_camaos,
            {{ process_null('idosodepenapanharlapismesa') }} as idoso_depen_apanhar_lapis_mesa,
            {{ process_null('idosodepenlevantardacadeira') }} as idoso_depen_levantar_da_cadeira,
            {{ process_null('idosodepencapazcaminhar3m') }} as idoso_depen_capaz_caminhar3m,
            {{ process_null('idosodepenvoltaresentar') }} as idoso_depen_voltar_sentar,
            {{ process_null('idosodepensaircama') }} as idoso_depen_sair_cama,
            {{ process_null('idosodepencapazvestir') }} as idoso_depen_capaz_vestir,
            {{ process_null('idosodepenpreprefeicoes') }} as idoso_depen_pre_pre_feicoes,
            {{ process_null('idosodepenfazercompras') }} as idoso_depen_fazer_compras,
            {{ process_null('idosodepenhaescadas') }} as idoso_depen_ha_escadas,
            {{ process_null('idosodepenhatapetessoltos') }} as idoso_depen_ha_tapetes_soltos,
            {{ process_null('idosodepenhacorrimaobanh') }} as idoso_depen_ha_corrimao_banh,
            {{ process_null('idosodepenquedaqtd') }} as idoso_depen_queda_qtd,
            {{ process_null('idosodepenalgajudarincapc') }} as idoso_depen_alg_ajudar_incapc,
            {{ process_null('idosodepenalgajudarincapcquem') }} as idoso_depen_alg_ajudar_incapc_quem,
            {{ process_null('idosodepenalgajudarincapcquemtomardecis') }} as idoso_depen_alg_ajudar_incapc_quem_tomar_decis,
            {{ process_null('katztomarbanho') }} as katz_tomar_banho,
            {{ process_null('katzvestirse') }} as katz_vestirse,
            {{ process_null('katzirwc') }} as katz_irwc,
            {{ process_null('katztransferencia') }} as katz_transferencia,
            {{ process_null('katzcontinencia') }} as katz_continencia,
            {{ process_null('katzalimentacao') }} as katz_alimentacao,
            {{ process_null('katzclassificacao') }} as katz_classificacao,
            {{ process_null('depquestionariopfeffer1') }} as dep_questionario_pfeffer1,
            {{ process_null('depquestionariopfeffer2') }} as dep_questionario_pfeffer2,
            {{ process_null('depquestionariopfeffer3') }} as dep_questionario_pfeffer3,
            {{ process_null('depquestionariopfeffer4') }} as dep_questionario_pfeffer4,
            {{ process_null('depquestionariopfeffer5') }} as dep_questionario_pfeffer5,
            {{ process_null('depquestionariopfeffer6') }} as dep_questionario_pfeffer6,
            {{ process_null('depquestionariopfeffer7') }} as dep_questionario_pfeffer7,
            {{ process_null('depquestionariopfeffer8') }} as dep_questionario_pfeffer8,
            {{ process_null('depquestionariopfeffer9') }} as dep_questionario_pfeffer9,
            {{ process_null('depquestionariopfeffer10') }} as dep_questionario_pfeffer10,
            {{ process_null('depquestionariopfeffer11') }} as dep_questionario_pfeffer11,
            {{ process_null('depquestionariopfefferpontos') }} as dep_questionario_pfeffer_pontos,
            {{ process_null('lawtonutilizartelefone') }} as lawton_utilizar_telefone,
            {{ process_null('lawtonplanespecial') }} as lawton_plane_special,
            {{ process_null('lawtonircompras') }} as lawton_ir_compras,
            {{ process_null('lawtonrefdiarias') }} as lawton_ref_diarias,
            {{ process_null('lawtonarrucasa') }} as lawton_arru_casa,
            {{ process_null('lawtoncuidcasa') }} as lawton_cuid_casa,
            {{ process_null('lawtoncuidroupa') }} as lawton_cuid_roupa,
            {{ process_null('lawtonmedadequadamente') }} as lawton_med_adequadamente,
            {{ process_null('lawtongerirdinheiro') }} as lawton_gerir_dinheiro,
            {{ process_null('lawtonpontuacao') }} as lawton_pontuacao,
            {{ process_null('tinnetiequilibrio') }} as tinneti_equilibrio,
            {{ process_null('tinnetilevantar') }} as tinneti_levantar,
            {{ process_null('tinnetilevantarten') }} as tinneti_levantar_ten,
            {{ process_null('tinnetiposlevantar') }} as tinneti_pos_levantar,
            {{ process_null('tinneti3campos') }} as tinneti_3_campos,
            {{ process_null('tinnetiolhos') }} as tinneti_olhos,
            {{ process_null('tinnetigirando360') }} as tinneti_girando360,
            {{ process_null('tinnetisentado') }} as tinneti_sentado,
            {{ process_null('tinnetiinimarcha') }} as tinneti_ini_marcha,
            {{ process_null('tinneticomppassosd') }} as tinneti_comp_passosd,
            {{ process_null('tinneticomppassose') }} as tinneti_comp_passose,
            {{ process_null('tinnetialtpassosd') }} as tinneti_alt_passosd,
            {{ process_null('tinnetialtpassose') }} as tinneti_alt_passose,
            {{ process_null('tinnetisimetria') }} as tinneti_simetria,
            {{ process_null('tinneticontinuidadepassos') }} as tinneti_continuidade_passos,
            {{ process_null('tinnetidirecao') }} as tinneti_direcao,
            {{ process_null('tinnetitronco') }} as tinneti_tronco,
            {{ process_null('tinnetitornozelos') }} as tinneti_tornozelos,
            {{ process_null('tinnetipontuacao') }} as tinneti_pontuacao,
            {{ process_null('ivcf20pluginidadequalsuaidade') }} as ivcf20_plugin_idade_qual_sua_idade,
            {{ process_null('ivcf20pluginautopercepcaosaudevcdiriadasuasaude') }} as ivcf20_plugin_autopercepcao_saude_vcd_iria_da_sua_saude,
            {{ process_null('ivcf20pluginatividadesvidadiariadeixoufazercompras') }} as ivcf20_plugin_atividades_vida_diaria_deixou_fazer_compras,
            {{ process_null('ivcf20pluginatividadesvidadiariadeixoucontrolardinheiro') }} as ivcf20_plugin_atividades_vida_diaria_deixou_controlar_dinheiro,
            {{ process_null('ivcf20pluginatividadesvidadiariadeixourealizartrabalhos') }} as ivcf20_plugin_atividades_vida_diaria_deixou_realizar_trabalhos,
            {{ process_null('ivcf20pluginatividadesvidadiariadeixoutomarbanho') }} as ivcf20_plugin_atividades_vida_diaria_deixou_tomar_banho,
            {{ process_null('ivcf20plugincognicaofamiliarfalouficandoesquecido') }} as ivcf20_plugin_cognicao_familiar_falou_ficando_esquecido,
            {{ process_null('ivcf20plugincognicaoesquecimentoestapiorandoultmeses') }} as ivcf20_plugin_cognicao_esquecimento_esta_piorando_ult_meses,
            {{ process_null('ivcf20plugincognicaoesquecimentoimpedindoatividadecotidiano') }} as ivcf20_plugin_cognicao_esquecimento_impedindo_atividade_cotidiano,
            {{ process_null('ivcf20pluginhumorultmesdesanimo') }} as ivcf20_plugin_humor_ult_mes_desanimo,
            {{ process_null('ivcf20pluginhumorperdeuinteresseatividade') }} as ivcf20_plugin_humor_perdeu_interesse_atividade,
            {{ process_null('ivcf20pluginmobilidadeincapazelevarbraco') }} as ivcf20_plugin_mobilidade_incapaz_elevar_braco,
            {{ process_null('ivcf20pluginmobilidadeincapazsegurarpeqobjetos') }} as ivcf20_plugin_mobilidade_incapaz_segurar_peq_objetos,
            {{ process_null('ivcf20pluginmobilidadetemalgumaquatrocondicoes') }} as ivcf20_plugin_mobilidade_tem_alguma_quatro_condicoes,
            {{ process_null('ivcf20pluginmobilidadedificuldadecaminhar') }} as ivcf20_plugin_mobilidade_dificuldade_caminhar,
            {{ process_null('ivcf20pluginmobilidadeteveduasmaisquedas') }} as ivcf20_plugin_mobilidade_teve_duas_mais_quedas,
            {{ process_null('ivcf20pluginmobilidadeperdeurinafezessemquerer') }} as ivcf20_plugin_mobilidade_perde_urina_fezes_sem_querer,
            {{ process_null('ivcf20plugincomunicacaovisao') }} as ivcf20_plugin_comunicacao_visao,
            {{ process_null('ivcf20plugincomunicacaoaudicao') }} as ivcf20_plugin_comunicacao_audicao,
            {{ process_null('ivcf20plugincomorbidadesmultiplastemalgumatrescondicoes') }} as ivcf20_plugin_comorbidades_multiplas_tem_alguma_tres_condicoes,
            {{ process_null('ivcf20pluginpontuacaofinal') }} as ivcf20_plugin_pontuacao_final,
            {{ process_null('ivcf20plugincorrelacao') }} as ivcf20_plugin_correlacao,
            {{ process_null('ves13pluginidadequalsuaidade') }} as ves13_plugin_idade_qual_sua_idade,
            {{ process_null('ves13pluginautopercepcaosaudevcdiriadasuasaude') }} as ves13_plugin_autopercepcao_saude_vcd_iria_da_sua_saude,
            {{ process_null('ves13pluginlimitacaofisicacurvar') }} as ves13_plugin_limitacao_fisica_curvar,
            {{ process_null('ves13pluginlimitacaofisicalevantar') }} as ves13_plugin_limitacao_fisica_levantar,
            {{ process_null('ves13pluginlimitacaofisicaelevar') }} as ves13_plugin_limitacao_fisica_elevar,
            {{ process_null('ves13pluginlimitacaofisicaescrever') }} as ves13_plugin_limitacao_fisica_escrever,
            {{ process_null('ves13pluginlimitacaofisicaandar') }} as ves13_plugin_limitacao_fisica_andar,
            {{ process_null('ves13pluginlimitacaofisicafazer') }} as ves13_plugin_limitacao_fisica_fazer,
            {{ process_null('ves13pluginincapacidadesdeixoufazercompras') }} as ves13_plugin_incapacidades_deixou_fazer_compras,
            {{ process_null('ves13pluginincapacidadesdeixoucontrolardinheiro') }} as ves13_plugin_incapacidades_deixou_controlar_dinheiro,
            {{ process_null('ves13pluginincapacidadesdeixoucaminharcasa') }} as ves13_plugin_incapacidades_deixou_caminhar_casa,
            {{ process_null('ves13pluginincapacidadesdeixourealizartrabalhos') }} as ves13_plugin_incapacidades_deixou_realizar_trabalhos,
            {{ process_null('ves13pluginincapacidadesdeixoutomarbanho') }} as ves13_plugin_incapacidades_deixou_tomar_banho,
            {{ process_null('ves13pluginpontuacaofinal') }} as ves13_plugin_pontuacao_final,
            {{ process_null('ves13plugincorrelacao') }} as ves13_plugin_correlacao,
            {{ process_null('ves13pluginprovidencias') }} as ves13_plugin_providencias,
            {{ process_null('depmmscalculoo') }} as dep_mms_calculo_o,
            {{ process_null('depmmscalculod') }} as dep_mms_calculo_d,
            {{ process_null('depmmscalculon') }} as dep_mms_calculo_n,
            {{ process_null('depmmscalculou') }} as dep_mms_calculo_u,
            {{ process_null('depmmscalculom') }} as dep_mms_calculo_m,
            {{ process_null('utresponsavel') }} as ut_responsavel,
            {{ process_null('utenteescolaridaderesponsavel') }} as utente_escolaridade_responsavel,
            safe_cast({{ process_null('utentedatanascimentoresponsavel') }} as datetime) as utente_data_nascimento_responsavel,
            {{ process_null('utentegrauparentescoresponsavel') }} as utente_grau_parentesco_responsavel,

            safe_cast(extracted_at as datetime) AS loaded_at,
            date(safe_cast(extracted_at as datetime)) as data_particao
        from idoso_deduplicados
    )

select
    *
from fato_idoso