{{
    config(
        alias="prenatal",
        materialized="table",
        schema="brutos_prontuario_vitacare_historico",
    )
}}

WITH

    source_prenatal AS (
        SELECT
            CONCAT(
                NULLIF({{ remove_double_quotes('id_cnes') }}, ''),
                '.',
                NULLIF({{ remove_double_quotes('acto_id') }}, '')
            ) AS id_prontuario_global,
            *
        FROM {{ source('brutos_prontuario_vitacare_historico_staging', 'prenatal') }}
    ),


      -- Using window function to deduplicate prenatal
    prenatal_deduplicados AS (
        SELECT
            *
        FROM (
            SELECT
                *,
                ROW_NUMBER() OVER (PARTITION BY id_prontuario_global ORDER BY extracted_at DESC) AS rn
            FROM source_prenatal
        )
        WHERE rn = 1
    ),

    fato_prenatal AS (
        SELECT
            -- PKs e Chaves
            id_prontuario_global,
            SAFE_CAST({{ remove_double_quotes('acto_id') }} AS NUMERIC) AS id_prontuario_local,
            {{ remove_double_quotes('id_cnes') }} AS cnes_unidade,

            {{ process_null(SAFE_CAST({{ remove_double_quotes('param_peso') }} AS NUMERIC)) }} AS param_peso,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('param_tamin') }} AS NUMERIC)) }} AS param_tamin,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('param_tamax') }} AS NUMERIC)) }} AS param_tamax,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('consseguintes_afu') }} AS NUMERIC)) }} AS consseguintes_afu,
            {{ process_null(remove_double_quotes('edema')) }} AS edema,
            {{ process_null(remove_double_quotes('observacoes')) }} AS observacoes,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('pconsulta_peso_habitual') }} AS NUMERIC)) }} AS pconsulta_peso_habitual,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('pconsulta_altura') }} AS NUMERIC)) }} AS pconsulta_altura,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('pconsulta_idade_gestacional') }} AS NUMERIC)) }} AS pconsulta_idade_gestacional,
            {{ process_null(remove_double_quotes('grupo_sanguineo_gravida')) }} AS grupo_sanguineo_gravida,
            {{ process_null(remove_double_quotes('pconsulta_grupo_sanguineo_pai')) }} AS pconsulta_grupo_sanguineo_pai,
            {{ process_null(remove_double_quotes('consseguintes_afuobs')) }} AS consseguintes_afuobs,
            {{ process_null(remove_double_quotes('pelvimetria_clinica')) }} AS pelvimetria_clinica,
            {{ process_null(remove_double_quotes('agraval_risco_prenatal_histo_reprod')) }} AS agraval_risco_prenatal_histo_reprod,
            {{ process_null(remove_double_quotes('agraval_risco_prenatal_histo_obstet_anterior')) }} AS agraval_risco_prenatal_histo_obstet_anterior,
            {{ process_null(remove_double_quotes('agraval_risco_prenatal_patol_associada')) }} AS agraval_risco_prenatal_patol_associada,
            {{ process_null(remove_double_quotes('agraval_risco_prenatal_gravidez_actual')) }} AS agraval_risco_prenatal_gravidez_actual,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('aval_risco_prenatal_total_indices') }} AS NUMERIC)) }} AS aval_risco_prenatal_total_indices,
            {{ process_null(remove_double_quotes('agraval_risco_prenatal_escala_nunomont')) }} AS agraval_risco_prenatal_escala_nunomont,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_glicemia_pos_50') }} AS NUMERIC)) }} AS exames_lab_glicemia_pos_50,
            {{ process_null(remove_double_quotes('exames_lab_tcoombs')) }} AS exames_lab_tcoombs,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_glicemia_jejum') }} AS NUMERIC)) }} AS exames_lab_glicemia_jejum,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_ptgo_0') }} AS NUMERIC)) }} AS exames_lab_ptgo_0,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_ptgo_60') }} AS NUMERIC)) }} AS exames_lab_ptgo_60,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_ptg_120') }} AS NUMERIC)) }} AS exames_lab_ptg_120,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_ptg_180') }} AS NUMERIC)) }} AS exames_lab_ptg_180,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_creatinemia') }} AS NUMERIC)) }} AS exames_lab_creatinemia,
            {{ process_null(remove_double_quotes('exames_lab_vdrl')) }} AS exames_lab_vdrl,
            {{ process_null(remove_double_quotes('exames_lab_toxoplasmose_imun')) }} AS exames_lab_toxoplasmose_imun,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_rubeola_igg') }} AS NUMERIC)) }} AS exames_lab_rubeola_igg,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_rubeola_igm') }} AS NUMERIC)) }} AS exames_lab_rubeola_igm,
            {{ process_null(remove_double_quotes('exames_lab_rubeola_imun')) }} AS exames_lab_rubeola_imun,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_aghbs') }} AS NUMERIC)) }} AS exames_lab_aghbs,
            {{ process_null(remove_double_quotes('exames_lab_hiv')) }} AS exames_lab_hiv,
            {{ process_null(remove_double_quotes('exames_lab_urocultura')) }} AS exames_lab_urocultura,
            {{ process_null(remove_double_quotes('exames_lab_urocultura_positiva')) }} AS exames_lab_urocultura_positiva,
            {{ process_null(remove_double_quotes('exame_clinic_mama_esq_inspeccao')) }} AS exame_clinic_mama_esq_inspeccao,
            {{ process_null(remove_double_quotes('exame_clini_cmama_esq_palpacao')) }} AS exame_clini_cmama_esq_palpacao,
            {{ process_null(remove_double_quotes('exame_clinic_mama_dir_inspeccao')) }} AS exame_clinic_mama_dir_inspeccao,
            {{ process_null(remove_double_quotes('exame_clinic_mama_dir_palpacao')) }} AS exame_clinic_mama_dir_palpacao,
            {{ process_null(remove_double_quotes('exame_ginec_vulva_vagina')) }} AS exame_ginec_vulva_vagina,
            {{ process_null(remove_double_quotes('colo_utero_exame')) }} AS colo_utero_exame,
            {{ process_null(remove_double_quotes('colo_utero_toque')) }} AS colo_utero_toque,
            {{ process_null(remove_double_quotes('exame_citologiares')) }} AS exame_citologiares,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('pconsulta_dum1') }} AS NUMERIC)) }} AS pconsulta_dum1,
            {{ process_null(remove_double_quotes('pconsulta_dpp1')) }} AS pconsulta_dpp1,
            {{ process_null(remove_double_quotes('agraval_risco_prenatal_obs')) }} AS agraval_risco_prenatal_obs,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('pconsulta_idade_gestacional_dias') }} AS NUMERIC)) }} AS pconsulta_idade_gestacional_dias,
            {{ process_null(remove_double_quotes('exame_clinic_mama_esq_inspeccao_obs')) }} AS exame_clinic_mama_esq_inspeccao_obs,
            {{ process_null(remove_double_quotes('exame_clinic_mama_dir_inspeccao_obs')) }} AS exame_clinic_mama_dir_inspeccao_obs,
            {{ process_null(remove_double_quotes('exame_clinic_mama_esq_palpacao_obs')) }} AS exame_clinic_mama_esq_palpacao_obs,
            {{ process_null(remove_double_quotes('exame_clinic_mama_dir_palpacao_obs')) }} AS exame_clinic_mama_dir_palpacao_obs,
            {{ process_null(remove_double_quotes('queixas_mam')) }} AS queixas_mam,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_eritrocitos') }} AS NUMERIC)) }} AS analises_eritrocitos,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_hemoglobina') }} AS NUMERIC)) }} AS analises_hemoglobina,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_hematocrito') }} AS NUMERIC)) }} AS analises_hematocrito,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_gm') }} AS NUMERIC)) }} AS analises_gm,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_hgm') }} AS NUMERIC)) }} AS analises_hgm,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_chgm') }} AS NUMERIC)) }} AS analises_chgm,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_leucocitos') }} AS NUMERIC)) }} AS analises_leucocitos,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_neutrifilos') }} AS NUMERIC)) }} AS analises_neutrifilos,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_eosinofilos') }} AS NUMERIC)) }} AS analises_eosinofilos,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_basofilos') }} AS NUMERIC)) }} AS analises_basofilos,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_linfocitos') }} AS NUMERIC)) }} AS analises_linfocitos,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('analises_monocitos') }} AS NUMERIC)) }} AS analises_monocitos,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_plaquetas') }} AS NUMERIC)) }} AS cseguintes_alalises_plaquetas,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_acidourico') }} AS NUMERIC)) }} AS cseguintes_alalises_acidourico,
            {{ process_null(remove_double_quotes('cseguintes_alalises_citomegalo_virus')) }} AS cseguintes_alalises_citomegalo_virus,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_achbs') }} AS NUMERIC)) }} AS cseguintes_alalises_achbs,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_achbc') }} AS NUMERIC)) }} AS cseguintes_alalises_achbc,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_achvc') }} AS NUMERIC)) }} AS cseguintes_alalises_achvc,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_alfa_proteina') }} AS NUMERIC)) }} AS cseguintes_alalises_alfa_proteina,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_inibinaa') }} AS NUMERIC)) }} AS cseguintes_alalises_inibinaa,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_estradiol') }} AS NUMERIC)) }} AS cseguintes_alalises_estradiol,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_hormona_beta_corionica') }} AS NUMERIC)) }} AS cseguintes_alalises_hormona_beta_corionica,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_tempo_protrombina') }} AS NUMERIC)) }} AS cseguintes_alalises_tempo_protrombina,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cseguintes_alalises_ttrombo_plastina_parcial') }} AS NUMERIC)) }} AS cseguintes_alalises_ttrombo_plastina_parcial,
            {{ process_null(remove_double_quotes('cseguintes_alalises_ecografia_obstetrica')) }} AS cseguintes_alalises_ecografia_obstetrica,
            {{ process_null(remove_double_quotes('alalises_eco_obstet_morfologica')) }} AS alalises_eco_obstet_morfologica,
            {{ process_null(remove_double_quotes('exame_citologia_resrccu')) }} AS exame_citologia_resrccu,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('pconsulta_dum1dias') }} AS NUMERIC)) }} AS pconsulta_dum1dias,
            {{ process_null(remove_double_quotes('data_mamografia')) }} AS data_mamografia,
            {{ process_null(remove_double_quotes('res_mamografias')) }} AS res_mamografias,
            {{ process_null(remove_double_quotes('analises_combur_combur')) }} AS analises_combur_combur,
            {{ process_null(remove_double_quotes('analises_combur_bilirrubina')) }} AS analises_combur_bilirrubina,
            {{ process_null(remove_double_quotes('analises_combur_urobilogenio')) }} AS analises_combur_urobilogenio,
            {{ process_null(remove_double_quotes('analises_combur_cetonas')) }} AS analises_combur_cetonas,
            {{ process_null(remove_double_quotes('analises_combur_glucose')) }} AS analises_combur_glucose,
            {{ process_null(remove_double_quotes('analises_combur_proteinas')) }} AS analises_combur_proteinas,
            {{ process_null(remove_double_quotes('analises_combur_sangue')) }} AS analises_combur_sangue,
            {{ process_null(remove_double_quotes('analises_combur_nitritos')) }} AS analises_combur_nitritos,
            {{ process_null(remove_double_quotes('analises_combur_ph')) }} AS analises_combur_ph,
            {{ process_null(remove_double_quotes('analises_combur_densidade')) }} AS analises_combur_densidade,
            {{ process_null(remove_double_quotes('analises_combur_leucocitos')) }} AS analises_combur_leucocitos,
            {{ process_null(remove_double_quotes('exames_lab_urocultur_ancolonias')) }} AS exames_lab_urocultur_ancolonias,
            {{ process_null(remove_double_quotes('data_resultado_citologia')) }} AS data_resultado_citologia,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('pconsulta_tamax') }} AS NUMERIC)) }} AS pconsulta_tamax,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('pconsulta_tamin') }} AS NUMERIC)) }} AS pconsulta_tamin,
            {{ process_null(remove_double_quotes('dta_eco')) }} AS dta_eco,
            {{ process_null(remove_double_quotes('res_mamografias_obs')) }} AS res_mamografias_obs,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('cons_seguintes_perimetro_abdominal') }} AS NUMERIC)) }} AS cons_seguintes_perimetro_abdominal,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('primeira_consulta_idade_gestacional') }} AS NUMERIC)) }} AS primeira_consulta_idade_gestacional,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('primeira_consulta_idade_gestacional_dias') }} AS NUMERIC)) }} AS primeira_consulta_idade_gestacional_dias,
            {{ process_null(remove_double_quotes('res_exames_lab_toxoplasmose_igg')) }} AS res_exames_lab_toxoplasmose_igg,
            {{ process_null(remove_double_quotes('res_exames_lab_toxoplasmose_igm')) }} AS res_exames_lab_toxoplasmose_igm,
            {{ process_null(remove_double_quotes('exames_lab_cultura_ag_patologicos')) }} AS exames_lab_cultura_ag_patologicos,
            {{ process_null(remove_double_quotes('exames_lab_cultura_tsa_sensiveis')) }} AS exames_lab_cultura_tsa_sensiveis,
            {{ process_null(remove_double_quotes('exames_lab_cultura_tsa_resistentes')) }} AS exames_lab_cultura_tsa_resistentes,
            {{ process_null(remove_double_quotes('exame_ginec_vulva_vagina_outras')) }} AS exame_ginec_vulva_vagina_outras,
            {{ process_null(remove_double_quotes('colo_utero_toque_outras')) }} AS colo_utero_toque_outras,
            {{ process_null(remove_double_quotes('classificacao_gestacao_alto_risco')) }} AS classificacao_gestacao_alto_risco,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('gestante_gestacoes_num') }} AS NUMERIC)) }} AS gestante_gestacoes_num,
            {{ process_null(remove_double_quotes('sifilis_tratamento_dose_1')) }} AS sifilis_tratamento_dose_1,
            {{ process_null(remove_double_quotes('sifilis_tratamento_dose_2')) }} AS sifilis_tratamento_dose_2,
            {{ process_null(remove_double_quotes('sifilis_tratamento_dose_3')) }} AS sifilis_tratamento_dose_3,
            {{ process_null(remove_double_quotes('sifilis_tratamento_de_parceiro')) }} AS sifilis_tratamento_de_parceiro,
            {{ process_null(remove_double_quotes('sifilis_inc_ou_efetuado_tratamento_parceiro_dose_1')) }} AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_1,
            {{ process_null(remove_double_quotes('sifilis_inc_ou_efetuado_tratamento_parceiro_dose_2')) }} AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_2,
            {{ process_null(remove_double_quotes('sifilis_inc_ou_efetuado_tratamento_parceiro_dose_3')) }} AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_3,
            {{ process_null(remove_double_quotes('sifilis_data_visita_domiciliar')) }} AS sifilis_data_visita_domiciliar,
            {{ process_null(remove_double_quotes('sifilis_motivo_visita_domiciliar')) }} AS sifilis_motivo_visita_domiciliar,
            {{ process_null(remove_double_quotes('sifilis_observacoes')) }} AS sifilis_observacoes,
            {{ process_null(remove_double_quotes('exames_lab_streptoccus_b')) }} AS exames_lab_streptoccus_b,
            {{ process_null(remove_double_quotes('exames_lab_streptoccus_b_obs')) }} AS exames_lab_streptoccus_b_obs,
            {{ process_null(remove_double_quotes('consulta_seguintes_intercorrencias')) }} AS consulta_seguintes_intercorrencias,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('exames_lab_hemoglobina_d') }} AS NUMERIC)) }} AS exames_lab_hemoglobina_d,
            {{ process_null(remove_double_quotes('exames_lab_vdrl_titulacao')) }} AS exames_lab_vdrl_titulacao,
            {{ process_null(remove_double_quotes('sifilis_teste_rapido_sifilis_parceiro')) }} AS sifilis_teste_rapido_sifilis_parceiro,
            {{ process_null(remove_double_quotes('sifilis_vdrl_parceiro')) }} AS sifilis_vdrl_parceiro,
            {{ process_null(remove_double_quotes('cons_seguintes_placenta_posicionamento')) }} AS cons_seguintes_placenta_posicionamento,
            {{ process_null(remove_double_quotes('cons_seguintes_placenta_sinais_risco')) }} AS cons_seguintes_placenta_sinais_risco,
            {{ process_null(remove_double_quotes('cons_seguintes_placenta_maturidade')) }} AS cons_seguintes_placenta_maturidade,
            {{ process_null(remove_double_quotes('cons_seguintes_placenta_observacoes')) }} AS cons_seguintes_placenta_observacoes,
            {{ process_null(remove_double_quotes('cons_seguintes_liquido_amniotico')) }} AS cons_seguintes_liquido_amniotico,
            {{ process_null(remove_double_quotes('cons_seguintes_liquido_amniotico_observacoes')) }} AS cons_seguintes_liquido_amniotico_observacoes,
            {{ process_null(remove_double_quotes('cseguintes_cardiotocografia')) }} AS cseguintes_cardiotocografia,
            {{ process_null(remove_double_quotes('sifilis_titulacao_parceiro')) }} AS sifilis_titulacao_parceiro,
            {{ process_null(remove_double_quotes('sifilis_esquema_tratamento_parceiro')) }} AS sifilis_esquema_tratamento_parceiro,
            {{ process_null(remove_double_quotes('exames_lab_agr_testes_rapidos_hiv')) }} AS exames_lab_agr_testes_rapidos_hiv,
            {{ process_null(remove_double_quotes('exames_lab_agr_testes_rapidos_hiv_positivo')) }} AS exames_lab_agr_testes_rapidos_hiv_positivo,
            {{ process_null(remove_double_quotes('smrpuerperiodata')) }} AS smrpuerperiodata,
            {{ process_null(remove_double_quotes('smlocalparto')) }} AS smlocalparto,
            {{ process_null(remove_double_quotes('smtipoparto')) }} AS smtipoparto,
            {{ process_null(remove_double_quotes('smresivaopuerpobs')) }} AS smresivaopuerpobs,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioparametrospeso') }} AS NUMERIC)) }} AS smpuerperioparametrospeso,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioparametrostamin') }} AS NUMERIC)) }} AS smpuerperioparametrostamin,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioparametrostamax') }} AS NUMERIC)) }} AS smpuerperioparametrostamax,
            SAFE_CAST({{ remove_double_quotes('smpuerperiocitologia') }} AS VARCHAR(5)) AS smpuerperiocitologia,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioalalisesplaquetas') }} AS NUMERIC)) }} AS smpuerperioalalisesplaquetas,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioalalisesglicemia') }} AS NUMERIC)) }} AS smpuerperioalalisesglicemia,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioalalisescreatinina') }} AS NUMERIC)) }} AS smpuerperioalalisescreatinina,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioalalisesgamagt') }} AS NUMERIC)) }} AS smpuerperioalalisesgamagt,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioalalisesgot') }} AS NUMERIC)) }} AS smpuerperioalalisesgot,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioalalisesgtp') }} AS NUMERIC)) }} AS smpuerperioalalisesgtp,
            {{ process_null(remove_double_quotes('smpuerperioalalisesbilirrubinas')) }} AS smpuerperioalalisesbilirrubinas,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('smpuerperioalaliseacidourico') }} AS NUMERIC)) }} AS smpuerperioalaliseacidourico,
            {{ process_null(remove_double_quotes('smpuerperiourocultura')) }} AS smpuerperiourocultura,
            {{ process_null(remove_double_quotes('classificacaotipoparto')) }} AS classificacaotipoparto,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('puerperiomcdtsfosfatasealcalina') }} AS NUMERIC)) }} AS puerperiomcdtsfosfatasealcalina,
            {{ process_null(remove_double_quotes('puerperiomcdtsurinai')) }} AS puerperiomcdtsurinai,
            {{ process_null(remove_double_quotes('puerperiomcdtsurinaiobs')) }} AS puerperiomcdtsurinaiobs,
            {{ process_null(remove_double_quotes('puerperiourocultura')) }} AS puerperiourocultura,
            {{ process_null(remove_double_quotes('puerperionumcolonias')) }} AS puerperionumcolonias,
            {{ process_null(remove_double_quotes('puerperioagentespatologicos')) }} AS puerperioagentespatologicos,
            {{ process_null(remove_double_quotes('puerperiotsasensiveis')) }} AS puerperiotsasensiveis,
            {{ process_null(remove_double_quotes('puerperiotsaresistentes')) }} AS puerperiotsaresistentes,
            {{ process_null(remove_double_quotes('puerperiomcdtsurinairesulltado')) }} AS puerperiomcdtsurinairesulltado,
            {{ process_null(remove_double_quotes('puerperiotermo')) }} AS puerperiotermo,
            {{ process_null(remove_double_quotes('puerperiorazaocesareo')) }} AS puerperiorazaocesareo,
            {{ process_null(remove_double_quotes('puerperiorh')) }} AS puerperiorh,
            {{ process_null(remove_double_quotes('puerperiogamaglobulinaantid')) }} AS puerperiogamaglobulinaantid,
            {{ process_null(remove_double_quotes('puerperiogamaglobulinaantiddata')) }} AS puerperiogamaglobulinaantiddata,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('gestantepuerperionumrecemnascidos') }} AS NUMERIC)) }} AS gestantepuerperionumrecemnascidos,
            {{ process_null(remove_double_quotes('gestantepuerperioamamentacao')) }} AS gestantepuerperioamamentacao,
            {{ process_null(remove_double_quotes('puerperiodataaborto')) }} AS puerperiodataaborto,
            {{ process_null(remove_double_quotes('puerperiotipoaborto')) }} AS puerperiotipoaborto,
            {{ process_null(SAFE_CAST({{ remove_double_quotes('puerperioidadegestacao') }} AS NUMERIC)) }} AS puerperioidadegestacao,
            {{ process_null(remove_double_quotes('gestantepuerperiocuretagem')) }} AS gestantepuerperiocuretagem,
            {{ process_null(remove_double_quotes('puerperiooutrotermoqual')) }} AS puerperiooutrotermoqual,
   
            {{ remove_double_quotes('extracted_at') }} AS extracted_at

        FROM prenatal_deduplicados
    )

SELECT
    *
FROM fato_prenatal