{{
    config(
        alias="prenatal", 
        materialized="table",
        schema="brutos_prontuario_vitacare_historico",
    )
}}

WITH

    source_prenatal AS (
        SELECT 
            CONCAT(
                NULLIF({{ remove_double_quotes('id_cnes') }}, ''), 
                '.',
                NULLIF({{ remove_double_quotes('acto_id') }}, '')
            ) AS id_prontuario_global,
            *
        FROM {{ source('brutos_vitacare_historic_staging', 'PRENATAL') }} 
    ),


      -- Using window function to deduplicate prenatal
    prenatal_deduplicados AS (
        SELECT
            *
        FROM (
            SELECT
                *,
                ROW_NUMBER() OVER (PARTITION BY id_prontuario_global ORDER BY extracted_at DESC) AS rn
            FROM source_prenatal
        )
        WHERE rn = 1
    ),

    fato_prenatal AS (
        SELECT
            -- PKs e Chaves
            id_prontuario_global,
            {{ remove_double_quotes('acto_id') }} AS id_prontuario_local,
            {{ remove_double_quotes('id_cnes') }} AS cnes_unidade,

            {{ remove_double_quotes('param_peso') }} AS param_peso,
            {{ remove_double_quotes('param_tamin') }} AS param_tamin,
            {{ remove_double_quotes('param_tamax') }} AS param_tamax,
            {{ remove_double_quotes('consseguintes_afu') }} AS consseguintes_afu,
            {{ remove_double_quotes('edema') }} AS edema,
            {{ remove_double_quotes('observacoes') }} AS observacoes,
            {{ remove_double_quotes('pconsulta_peso_habitual') }} AS pconsulta_peso_habitual,
            {{ remove_double_quotes('pconsulta_altura') }} AS pconsulta_altura,
            {{ remove_double_quotes('pconsulta_idade_gestacional') }} AS pconsulta_idade_gestacional,
            {{ remove_double_quotes('grupo_sanguineo_gravida') }} AS grupo_sanguineo_gravida,
            {{ remove_double_quotes('pconsulta_grupo_sanguineo_pai') }} AS pconsulta_grupo_sanguineo_pai,
            {{ remove_double_quotes('consseguintes_afuobs') }} AS consseguintes_afuobs,
            {{ remove_double_quotes('pelvimetria_clinica') }} AS pelvimetria_clinica,
            {{ remove_double_quotes('agraval_risco_prenatal_histo_reprod') }} AS agraval_risco_prenatal_histo_reprod,
            {{ remove_double_quotes('agraval_risco_prenatal_histo_obstet_anterior') }} AS agraval_risco_prenatal_histo_obstet_anterior,
            {{ remove_double_quotes('agraval_risco_prenatal_patol_associada') }} AS agraval_risco_prenatal_patol_associada,
            {{ remove_double_quotes('agraval_risco_prenatal_gravidez_actual') }} AS agraval_risco_prenatal_gravidez_actual,
            {{ remove_double_quotes('aval_risco_prenatal_total_indices') }} AS aval_risco_prenatal_total_indices,
            {{ remove_double_quotes('agraval_risco_prenatal_escala_nunomont') }} AS agraval_risco_prenatal_escala_nunomont,
            {{ remove_double_quotes('exames_lab_glicemia_pos_50') }} AS exames_lab_glicemia_pos_50,
            {{ remove_double_quotes('exames_lab_tcoombs') }} AS exames_lab_tcoombs,
            {{ remove_double_quotes('exames_lab_glicemia_jejum') }} AS exames_lab_glicemia_jejum,
            {{ remove_double_quotes('exames_lab_ptgo_0') }} AS exames_lab_ptgo_0,
            {{ remove_double_quotes('exames_lab_ptgo_60') }} AS exames_lab_ptgo_60,
            {{ remove_double_quotes('exames_lab_ptg_120') }} AS exames_lab_ptg_120,
            {{ remove_double_quotes('exames_lab_ptg_180') }} AS exames_lab_ptg_180,
            {{ remove_double_quotes('exames_lab_creatinemia') }} AS exames_lab_creatinemia,
            {{ remove_double_quotes('exames_lab_vdrl') }} AS exames_lab_vdrl,
            {{ remove_double_quotes('exames_lab_toxoplasmose_imun') }} AS exames_lab_toxoplasmose_imun,
            {{ remove_double_quotes('exames_lab_rubeola_igg') }} AS exames_lab_rubeola_igg,
            {{ remove_double_quotes('exames_lab_rubeola_igm') }} AS exames_lab_rubeola_igm,
            {{ remove_double_quotes('exames_lab_rubeola_imun') }} AS exames_lab_rubeola_imun,
            {{ remove_double_quotes('exames_lab_aghbs') }} AS exames_lab_aghbs,
            {{ remove_double_quotes('exames_lab_hiv') }} AS exames_lab_hiv,
            {{ remove_double_quotes('exames_lab_urocultura') }} AS exames_lab_urocultura,
            {{ remove_double_quotes('exames_lab_urocultura_positiva') }} AS exames_lab_urocultura_positiva,
            {{ remove_double_quotes('exame_clinic_mama_esq_inspeccao') }} AS exame_clinic_mama_esq_inspeccao,
            {{ remove_double_quotes('exame_clini_cmama_esq_palpacao') }} AS exame_clini_cmama_esq_palpacao,
            {{ remove_double_quotes('exame_clinic_mama_dir_inspeccao') }} AS exame_clinic_mama_dir_inspeccao,
            {{ remove_double_quotes('exame_clinic_mama_dir_palpacao') }} AS exame_clinic_mama_dir_palpacao,
            {{ remove_double_quotes('exame_ginec_vulva_vagina') }} AS exame_ginec_vulva_vagina,
            {{ remove_double_quotes('colo_utero_exame') }} AS colo_utero_exame,
            {{ remove_double_quotes('colo_utero_toque') }} AS colo_utero_toque,
            {{ remove_double_quotes('exame_citologiares') }} AS exame_citologiares,
            {{ remove_double_quotes('pconsulta_dum1') }} AS pconsulta_dum1,
            {{ remove_double_quotes('pconsulta_dpp1') }} AS pconsulta_dpp1,
            {{ remove_double_quotes('agraval_risco_prenatal_obs') }} AS agraval_risco_prenatal_obs,
            {{ remove_double_quotes('pconsulta_idade_gestacional_dias') }} AS pconsulta_idade_gestacional_dias,
            {{ remove_double_quotes('exame_clinic_mama_esq_inspeccao_obs') }} AS exame_clinic_mama_esq_inspeccao_obs,
            {{ remove_double_quotes('exame_clinic_mama_dir_inspeccao_obs') }} AS exame_clinic_mama_dir_inspeccao_obs,
            {{ remove_double_quotes('exame_clinic_mama_esq_palpacao_obs') }} AS exame_clinic_mama_esq_palpacao_obs,
            {{ remove_double_quotes('exame_clinic_mama_dir_palpacao_obs') }} AS exame_clinic_mama_dir_palpacao_obs,
            {{ remove_double_quotes('queixas_mam') }} AS queixas_mam,
            {{ remove_double_quotes('analises_eritrocitos') }} AS analises_eritrocitos,
            {{ remove_double_quotes('analises_hemoglobina') }} AS analises_hemoglobina,
            {{ remove_double_quotes('analises_hematocrito') }} AS analises_hematocrito,
            {{ remove_double_quotes('analises_gm') }} AS analises_gm,
            {{ remove_double_quotes('analises_hgm') }} AS analises_hgm,
            {{ remove_double_quotes('analises_chgm') }} AS analises_chgm,
            {{ remove_double_quotes('analises_leucocitos') }} AS analises_leucocitos,
            {{ remove_double_quotes('analises_neutrifilos') }} AS analises_neutrifilos,
            {{ remove_double_quotes('analises_eosinofilos') }} AS analises_eosinofilos,
            {{ remove_double_quotes('analises_basofilos') }} AS analises_basofilos,
            {{ remove_double_quotes('analises_linfocitos') }} AS analises_linfocitos,
            {{ remove_double_quotes('analises_monocitos') }} AS analises_monocitos,
            {{ remove_double_quotes('cseguintes_alalises_plaquetas') }} AS cseguintes_alalises_plaquetas,
            {{ remove_double_quotes('cseguintes_alalises_acidourico') }} AS cseguintes_alalises_acidourico,
            {{ remove_double_quotes('cseguintes_alalises_citomegalo_virus') }} AS cseguintes_alalises_citomegalo_virus,
            {{ remove_double_quotes('cseguintes_alalises_achbs') }} AS cseguintes_alalises_achbs,
            {{ remove_double_quotes('cseguintes_alalises_achbc') }} AS cseguintes_alalises_achbc,
            {{ remove_double_quotes('cseguintes_alalises_achvc') }} AS cseguintes_alalises_achvc,
            {{ remove_double_quotes('cseguintes_alalises_alfa_proteina') }} AS cseguintes_alalises_alfa_proteina,
            {{ remove_double_quotes('cseguintes_alalises_inibinaa') }} AS cseguintes_alalises_inibinaa,
            {{ remove_double_quotes('cseguintes_alalises_estradiol') }} AS cseguintes_alalises_estradiol,
            {{ remove_double_quotes('cseguintes_alalises_hormona_beta_corionica') }} AS cseguintes_alalises_hormona_beta_corionica,
            {{ remove_double_quotes('cseguintes_alalises_tempo_protrombina') }} AS cseguintes_alalises_tempo_protrombina,
            {{ remove_double_quotes('cseguintes_alalises_ttrombo_plastina_parcial') }} AS cseguintes_alalises_ttrombo_plastina_parcial,
            {{ remove_double_quotes('cseguintes_alalises_ecografia_obstetrica') }} AS cseguintes_alalises_ecografia_obstetrica,
            {{ remove_double_quotes('alalises_eco_obstet_morfologica') }} AS alalises_eco_obstet_morfologica,
            {{ remove_double_quotes('exame_citologia_resrccu') }} AS exame_citologia_resrccu,
            {{ remove_double_quotes('pconsulta_dum1dias') }} AS pconsulta_dum1dias,
            {{ remove_double_quotes('data_mamografia') }} AS data_mamografia,
            {{ remove_double_quotes('res_mamografias') }} AS res_mamografias,
            {{ remove_double_quotes('analises_combur_combur') }} AS analises_combur_combur,
            {{ remove_double_quotes('analises_combur_bilirrubina') }} AS analises_combur_bilirrubina,
            {{ remove_double_quotes('analises_combur_urobilogenio') }} AS analises_combur_urobilogenio,
            {{ remove_double_quotes('analises_combur_cetonas') }} AS analises_combur_cetonas,
            {{ remove_double_quotes('analises_combur_glucose') }} AS analises_combur_glucose,
            {{ remove_double_quotes('analises_combur_proteinas') }} AS analises_combur_proteinas,
            {{ remove_double_quotes('analises_combur_sangue') }} AS analises_combur_sangue,
            {{ remove_double_quotes('analises_combur_nitritos') }} AS analises_combur_nitritos,
            {{ remove_double_quotes('analises_combur_ph') }} AS analises_combur_ph,
            {{ remove_double_quotes('analises_combur_densidade') }} AS analises_combur_densidade,
            {{ remove_double_quotes('analises_combur_leucocitos') }} AS analises_combur_leucocitos,
            {{ remove_double_quotes('exames_lab_urocultur_ancolonias') }} AS exames_lab_urocultur_ancolonias,
            {{ remove_double_quotes('data_resultado_citologia') }} AS data_resultado_citologia,
            {{ remove_double_quotes('pconsulta_tamax') }} AS pconsulta_tamax,
            {{ remove_double_quotes('pconsulta_tamin') }} AS pconsulta_tamin,
            {{ remove_double_quotes('dta_eco') }} AS dta_eco,
            {{ remove_double_quotes('res_mamografias_obs') }} AS res_mamografias_obs,
            {{ remove_double_quotes('cons_seguintes_perimetro_abdominal') }} AS cons_seguintes_perimetro_abdominal,
            {{ remove_double_quotes('primeira_consulta_idade_gestacional') }} AS primeira_consulta_idade_gestacional,
            {{ remove_double_quotes('primeira_consulta_idade_gestacional_dias') }} AS primeira_consulta_idade_gestacional_dias,
            {{ remove_double_quotes('res_exames_lab_toxoplasmose_igg') }} AS res_exames_lab_toxoplasmose_igg,
            {{ remove_double_quotes('res_exames_lab_toxoplasmose_igm') }} AS res_exames_lab_toxoplasmose_igm,
            {{ remove_double_quotes('exames_lab_cultura_ag_patologicos') }} AS exames_lab_cultura_ag_patologicos,
            {{ remove_double_quotes('exames_lab_cultura_tsa_sensiveis') }} AS exames_lab_cultura_tsa_sensiveis,
            {{ remove_double_quotes('exames_lab_cultura_tsa_resistentes') }} AS exames_lab_cultura_tsa_resistentes,
            {{ remove_double_quotes('exame_ginec_vulva_vagina_outras') }} AS exame_ginec_vulva_vagina_outras,
            {{ remove_double_quotes('colo_utero_toque_outras') }} AS colo_utero_toque_outras,
            {{ remove_double_quotes('classificacao_gestacao_alto_risco') }} AS classificacao_gestacao_alto_risco,
            {{ remove_double_quotes('gestante_gestacoes_num') }} AS gestante_gestacoes_num,
            {{ remove_double_quotes('sifilis_tratamento_dose_1') }} AS sifilis_tratamento_dose_1,
            {{ remove_double_quotes('sifilis_tratamento_dose_2') }} AS sifilis_tratamento_dose_2,
            {{ remove_double_quotes('sifilis_tratamento_dose_3') }} AS sifilis_tratamento_dose_3,
            {{ remove_double_quotes('sifilis_tratamento_de_parceiro') }} AS sifilis_tratamento_de_parceiro,
            {{ remove_double_quotes('sifilis_inc_ou_efetuado_tratamento_parceiro_dose_1') }} AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_1,
            {{ remove_double_quotes('sifilis_inc_ou_efetuado_tratamento_parceiro_dose_2') }} AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_2,
            {{ remove_double_quotes('sifilis_inc_ou_efetuado_tratamento_parceiro_dose_3') }} AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_3,
            {{ remove_double_quotes('sifilis_data_visita_domiciliar') }} AS sifilis_data_visita_domiciliar,
            {{ remove_double_quotes('sifilis_motivo_visita_domiciliar') }} AS sifilis_motivo_visita_domiciliar,
            {{ remove_double_quotes('sifilis_observacoes') }} AS sifilis_observacoes,
            {{ remove_double_quotes('exames_lab_streptoccus_b') }} AS exames_lab_streptoccus_b,
            {{ remove_double_quotes('exames_lab_streptoccus_b_obs') }} AS exames_lab_streptoccus_b_obs,
            {{ remove_double_quotes('consulta_seguintes_intercorrencias') }} AS consulta_seguintes_intercorrencias,
            {{ remove_double_quotes('exames_lab_hemoglobina_d') }} AS exames_lab_hemoglobina_d,
            {{ remove_double_quotes('exames_lab_vdrl_titulacao') }} AS exames_lab_vdrl_titulacao,
            {{ remove_double_quotes('sifilis_teste_rapido_sifilis_parceiro') }} AS sifilis_teste_rapido_sifilis_parceiro,
            {{ remove_double_quotes('sifilis_vdrl_parceiro') }} AS sifilis_vdrl_parceiro,
            {{ remove_double_quotes('cons_seguintes_placenta_posicionamento') }} AS cons_seguintes_placenta_posicionamento,
            {{ remove_double_quotes('cons_seguintes_placenta_sinais_risco') }} AS cons_seguintes_placenta_sinais_risco,
            {{ remove_double_quotes('cons_seguintes_placenta_maturidade') }} AS cons_seguintes_placenta_maturidade,
            {{ remove_double_quotes('cons_seguintes_placenta_observacoes') }} AS cons_seguintes_placenta_observacoes,
            {{ remove_double_quotes('cons_seguintes_liquido_amniotico') }} AS cons_seguintes_liquido_amniotico,
            {{ remove_double_quotes('cons_seguintes_liquido_amniotico_observacoes') }} AS cons_seguintes_liquido_amniotico_observacoes,
            {{ remove_double_quotes('cseguintes_cardiotocografia') }} AS cseguintes_cardiotocografia,
            {{ remove_double_quotes('sifilis_titulacao_parceiro') }} AS sifilis_titulacao_parceiro,
            {{ remove_double_quotes('sifilis_esquema_tratamento_parceiro') }} AS sifilis_esquema_tratamento_parceiro,
            {{ remove_double_quotes('exames_lab_agr_testes_rapidos_hiv') }} AS exames_lab_agr_testes_rapidos_hiv,
            {{ remove_double_quotes('exames_lab_agr_testes_rapidos_hiv_positivo') }} AS exames_lab_agr_testes_rapidos_hiv_positivo,
            {{ remove_double_quotes('smrpuerperiodata') }} AS smrpuerperiodata,
            {{ remove_double_quotes('smlocalparto') }} AS smlocalparto,
            {{ remove_double_quotes('smtipoparto') }} AS smtipoparto,
            {{ remove_double_quotes('smresivaopuerpobs') }} AS smresivaopuerpobs,
            {{ remove_double_quotes('smpuerperioparametrospeso') }} AS smpuerperioparametrospeso,
            {{ remove_double_quotes('smpuerperioparametrostamin') }} AS smpuerperioparametrostamin,
            {{ remove_double_quotes('smpuerperioparametrostamax') }} AS smpuerperioparametrostamax,
            {{ remove_double_quotes('smpuerperiocitologia') }} AS smpuerperiocitologia,
            {{ remove_double_quotes('smpuerperioalalisesplaquetas') }} AS smpuerperioalalisesplaquetas,
            {{ remove_double_quotes('smpuerperioalalisesglicemia') }} AS smpuerperioalalisesglicemia,
            {{ remove_double_quotes('smpuerperioalalisescreatinina') }} AS smpuerperioalalisescreatinina,
            {{ remove_double_quotes('smpuerperioalalisesgamagt') }} AS smpuerperioalalisesgamagt,
            {{ remove_double_quotes('smpuerperioalalisesgot') }} AS smpuerperioalalisesgot,
            {{ remove_double_quotes('smpuerperioalalisesgtp') }} AS smpuerperioalalisesgtp,
            {{ remove_double_quotes('smpuerperioalalisesbilirrubinas') }} AS smpuerperioalalisesbilirrubinas,
            {{ remove_double_quotes('smpuerperioalaliseacidourico') }} AS smpuerperioalaliseacidourico,
            {{ remove_double_quotes('smpuerperiourocultura') }} AS smpuerperiourocultura,
            {{ remove_double_quotes('classificacaotipoparto') }} AS classificacaotipoparto,
            {{ remove_double_quotes('puerperiomcdtsfosfatasealcalina') }} AS puerperiomcdtsfosfatasealcalina,
            {{ remove_double_quotes('puerperiomcdtsurinai') }} AS puerperiomcdtsurinai,
            {{ remove_double_quotes('puerperiomcdtsurinaiobs') }} AS puerperiomcdtsurinaiobs,
            {{ remove_double_quotes('puerperiourocultura') }} AS puerperiourocultura,
            {{ remove_double_quotes('puerperionumcolonias') }} AS puerperionumcolonias,
            {{ remove_double_quotes('puerperioagentespatologicos') }} AS puerperioagentespatologicos,
            {{ remove_double_quotes('puerperiotsasensiveis') }} AS puerperiotsasensiveis,
            {{ remove_double_quotes('puerperiotsaresistentes') }} AS puerperiotsaresistentes,
            {{ remove_double_quotes('puerperiomcdtsurinairesulltado') }} AS puerperiomcdtsurinairesulltado,
            {{ remove_double_quotes('puerperiotermo') }} AS puerperiotermo,
            {{ remove_double_quotes('puerperiorazaocesareo') }} AS puerperiorazaocesareo,
            {{ remove_double_quotes('puerperiorh') }} AS puerperiorh,
            {{ remove_double_quotes('puerperiogamaglobulinaantid') }} AS puerperiogamaglobulinaantid,
            {{ remove_double_quotes('puerperiogamaglobulinaantiddata') }} AS puerperiogamaglobulinaantiddata,
            {{ remove_double_quotes('gestantepuerperionumrecemnascidos') }} AS gestantepuerperionumrecemnascidos,
            {{ remove_double_quotes('gestantepuerperioamamentacao') }} AS gestantepuerperioamamentacao,
            {{ remove_double_quotes('puerperiodataaborto') }} AS puerperiodataaborto,
            {{ remove_double_quotes('puerperiotipoaborto') }} AS puerperiotipoaborto,
            {{ remove_double_quotes('puerperioidadegestacao') }} AS puerperioidadegestacao,
            {{ remove_double_quotes('gestantepuerperiocuretagem') }} AS gestantepuerperiocuretagem,
            {{ remove_double_quotes('puerperiooutrotermoqual') }} AS puerperiooutrotermoqual,
   
            {{ remove_double_quotes('extracted_at') }} AS extracted_at

        FROM prenatal_deduplicados
    )

SELECT
    *
FROM fato_prenatal