{{
    config(
        alias        = "sinan__tuberculose_sinan",
        materialized = "table",
        tags         = ["subpav", "sinan"],
        cluster_by   = ["id", "nu_notificacao", "co_unidade_notificacao"]
    )
}}

with
    source as (
        select *
        from {{ source("brutos_plataforma_subpav_staging", "subpav_sinan__tuberculose_sinan") }}
    ),

    sem_duplicatas as (
        select *
        from source
        qualify
        row_number() over (
            partition by id, nu_notificacao, co_unidade_notificacao
            order by coalesce(timestamp,dt_notificacao, datalake_loaded_at) DESC
        ) = 1
    ),

    extrair_informacoes as (
        select
            SAFE_CAST({{ process_null('id') }} AS INT64)                                    AS id,
            {{ process_null('nu_notificacao') }}                                            AS nu_notificacao,
            SAFE_CAST({{ process_null('dt_notificacao') }} AS DATE)                         AS dt_notificacao,
            {{ process_null('co_cid') }}                                                    AS co_cid,
            {{ process_null('co_municipio_notificacao') }}                                  AS co_municipio_notificacao,
            {{ process_null('ap_res') }}                                                    AS ap_res,
            {{ process_null('chave_unica') }}                                               AS chave_unica,
            {{ process_null('cnes_not') }}                                                  AS cnes_not,
            {{ process_null('ap_not') }}                                                    AS ap_not,
            {{ process_null('cnes_res') }}                                                  AS cnes_res,
            {{ process_null('cod_area_res') }}                                              AS cod_area_res,
            {{ process_null('cod_microa_res') }}                                            AS cod_microa_res,
            SAFE_CAST({{ process_null('co_bairro_infeccao') }} AS INT64)                    AS co_bairro_infeccao,
            SAFE_CAST({{ process_null('co_bairro_residencia') }} AS INT64)                  AS co_bairro_residencia,
            SAFE_CAST({{ process_null('co_bairro_residencia_atual') }} AS NUMERIC)          AS co_bairro_residencia_atual,
            SAFE_CAST({{ process_null('co_cbo_ocupacao') }} AS NUMERIC)                     AS co_cbo_ocupacao,
            {{ process_null('co_distrito_infeccao') }}                                      AS co_distrito_infeccao,
            {{ process_null('co_distrito_residencia') }}                                    AS co_distrito_residencia,
            SAFE_CAST({{ process_null('co_distrito_residencia_atual') }} AS NUMERIC)        AS co_distrito_residencia_atual,
            SAFE_CAST({{ process_null('co_geo_campo_1') }} AS INT64)                        AS co_geo_campo_1,
            SAFE_CAST({{ process_null('co_geo_campo_2') }} AS INT64)                        AS co_geo_campo_2,
            SAFE_CAST({{ process_null('co_logradouro_residencia') }} AS INT64)              AS co_logradouro_residencia,
            {{ process_null('co_municipio_atual') }}                                        AS co_municipio_atual,
            {{ process_null('co_municipio_infeccao') }}                                     AS co_municipio_infeccao,
            {{ process_null('co_municipio_residencia') }}                                   AS co_municipio_residencia,
            {{ process_null('co_municipio_residencia_atual') }}                             AS co_municipio_residencia_atual,
            {{ process_null('co_municipio_transf') }}                                       AS co_municipio_transf,
            SAFE_CAST({{ process_null('co_pais_infeccao') }} AS INT64)                      AS co_pais_infeccao,
            {{ process_null('co_pais_residencia') }}                                        AS co_pais_residencia,
            {{ process_null('co_uf_atual') }}                                               AS co_uf_atual,
            {{ process_null('co_uf_infeccao') }}                                            AS co_uf_infeccao,
            {{ process_null('co_uf_notificacao') }}                                         AS co_uf_notificacao,
            {{ process_null('co_uf_residencia') }}                                          AS co_uf_residencia,
            {{ process_null('co_uf_residencia_atual') }}                                     AS co_uf_residencia_atual,
            {{ process_null('co_uf_transf') }}                                              AS co_uf_transf,
            SAFE_CAST({{ process_null('co_unidade_infeccao') }} AS INT64)                   AS co_unidade_infeccao,
            SAFE_CAST({{ process_null('co_unidade_notificacao') }} AS INT64)                AS co_unidade_notificacao,
            SAFE_CAST({{ process_null('co_unidade_saude_atual') }} AS NUMERIC)              AS co_unidade_saude_atual,
            SAFE_CAST({{ process_null('cpf_mae') }} AS INT64)                                AS cpf_mae,
            {{ process_null('cpf_notificante') }}                                           AS cpf_notificante,
            {{ process_null('cpf_paciente') }}                                              AS cpf_paciente,
            {{ process_null('dnv_paciente') }}                                              AS dnv_paciente,
            {{ process_null('ds_agravo_outro') }}                                           AS ds_agravo_outro,
            {{ process_null('ds_chave_fonetica') }}                                         AS ds_chave_fonetica,
            {{ process_null('ds_classificacao_final') }}                                    AS ds_classificacao_final,
            {{ process_null('ds_complemento_residencia') }}                                 AS ds_complemento_residencia,
            {{ process_null('ds_delimitacao_surto_outro') }}                                AS ds_delimitacao_surto_outro,
            {{ process_null('ds_droga_outro') }}                                            AS ds_droga_outro,
            {{ process_null('ds_evolucao_caso_outro') }}                                    AS ds_evolucao_caso_outro,
            {{ process_null('ds_extrapulmonar_outro') }}                                     AS ds_extrapulmonar_outro,
            {{ process_null('ds_identificador_registro') }}                                  AS ds_identificador_registro,
            {{ process_null('ds_local_infeccao_outro') }}                                    AS ds_local_infeccao_outro,
            {{ process_null('ds_local_outro') }}                                            AS ds_local_outro,
            {{ process_null('ds_modo_infeccao_outro') }}                                     AS ds_modo_infeccao_outro,
            {{ process_null('ds_observacao') }}                                             AS ds_observacao,
            {{ process_null('ds_referencia_residencia') }}                                   AS ds_referencia_residencia,
            {{ process_null('ds_semana_notificacao') }}                                      AS ds_semana_notificacao,
            {{ process_null('ds_semana_sintoma') }}                                         AS ds_semana_sintoma,
            {{ process_null('ds_soundex') }}                                                AS ds_soundex,
            {{ process_null('ds_veiculo_transmissao_outro') }}                               AS ds_veiculo_transmissao_outro,
            SAFE_CAST({{ process_null('dt_alteracao') }} AS DATE)                            AS dt_alteracao,
            SAFE_CAST({{ process_null('dt_diagnostico_sintoma') }} AS DATE)                  AS dt_diagnostico_sintoma,
            SAFE_CAST({{ process_null('dt_digitacao') }} AS DATE)                            AS dt_digitacao,
            SAFE_CAST({{ process_null('dt_encerramento') }} AS DATE)                         AS dt_encerramento,
            SAFE_CAST({{ process_null('dt_inicio_tratamento') }} AS DATE)                    AS dt_inicio_tratamento,
            SAFE_CAST({{ process_null('dt_investigacao') }} AS DATE)                         AS dt_investigacao,
            SAFE_CAST({{ process_null('dt_mudanca_tratamento') }} AS DATE)                   AS dt_mudanca_tratamento,
            SAFE_CAST({{ process_null('dt_nascimento') }} AS DATE)                           AS dt_nascimento,
            SAFE_CAST({{ process_null('dt_notificacao_atual') }} AS DATE)                    AS dt_notificacao_atual,
            SAFE_CAST({{ process_null('dt_obito') }} AS DATE)                                AS dt_obito,
            SAFE_CAST({{ process_null('dt_transf_dm') }} AS DATE)                            AS dt_transf_dm,
            SAFE_CAST({{ process_null('dt_transf_rm') }} AS DATE)                            AS dt_transf_rm,
            SAFE_CAST({{ process_null('dt_transf_rs') }} AS DATE)                            AS dt_transf_rs,
            SAFE_CAST({{ process_null('dt_transf_se') }} AS DATE)                            AS dt_transf_se,
            SAFE_CAST({{ process_null('dt_transf_sm') }} AS DATE)                            AS dt_transf_sm,
            SAFE_CAST({{ process_null('dt_transf_us') }} AS DATE)                            AS dt_transf_us,
            SAFE_CAST({{ process_null('finalizado') }} AS INT64)                             AS finalizado,
            {{ process_null('justificativa') }}                                             AS justificativa,
            {{ process_null('justificativa_paciente') }}                                     AS justificativa_paciente,
            {{ process_null('lat') }}                                                       AS lat,
            {{ process_null('lng') }}                                                       AS lng,
            {{ process_null('nome_ub_not') }}                                               AS nome_ub_not,
            {{ process_null('notif_assistente') }}                                          AS notif_assistente,
            {{ process_null('no_bairro_infeccao') }}                                        AS no_bairro_infeccao,
            {{ process_null('no_bairro_residencia') }}                                      AS no_bairro_residencia,
            {{ process_null('no_bairro_residencia_atual') }}                                 AS no_bairro_residencia_atual,
            {{ process_null('no_localidade_infeccao') }}                                     AS no_localidade_infeccao,
            {{ process_null('no_logradouro_residencia') }}                                   AS no_logradouro_residencia,
            {{ process_null('no_nome_mae') }}                                               AS no_nome_mae,
            {{ process_null('no_nome_paciente') }}                                          AS no_nome_paciente,
            {{ process_null('soundex_busca') }}                                             AS soundex_busca,
            {{ process_null('soundex_busca2') }}                                            AS soundex_busca2,
            {{ process_null('nu_cartao_sus') }}                                             AS nu_cartao_sus,
            SAFE_CAST({{ process_null('nu_caso_examinado') }} AS INT64)                      AS nu_caso_examinado,
            SAFE_CAST({{ process_null('nu_caso_positivo') }} AS INT64)                       AS nu_caso_positivo,
            SAFE_CAST({{ process_null('nu_caso_suspeito') }} AS INT64)                       AS nu_caso_suspeito,
            {{ process_null('nu_cep_residencia') }}                                         AS nu_cep_residencia,
            {{ process_null('nu_cep_residencia_atual') }}                                    AS nu_cep_residencia_atual,
            SAFE_CAST({{ process_null('nu_contato') }} AS NUMERIC)                           AS nu_contato,
            SAFE_CAST({{ process_null('nu_contato_examinado') }} AS NUMERIC)                 AS nu_contato_examinado,
            SAFE_CAST({{ process_null('nu_contato_identificados') }} AS NUMERIC)             AS nu_contato_identificados,
            {{ process_null('nu_ddd_residencia') }}                                         AS nu_ddd_residencia,
            SAFE_CAST({{ process_null('nu_idade') }} AS INT64)                               AS nu_idade,
            {{ process_null('nu_lote_horizontal') }}                                        AS nu_lote_horizontal,
            {{ process_null('nu_lote_vertical') }}                                          AS nu_lote_vertical,
            {{ process_null('nu_notificacao_atual') }}                                       AS nu_notificacao_atual,
            {{ process_null('nu_prontuario') }}                                             AS nu_prontuario,
            {{ process_null('nu_prontuario_atual') }}                                       AS nu_prontuario_atual,
            {{ process_null('nu_residencia') }}                                             AS nu_residencia,
            {{ process_null('nu_telefone_residencia') }}                                     AS nu_telefone_residencia,
            SAFE_CAST({{ process_null('situacao_de_rua') }} AS INT64)                        AS situacao_de_rua,
            {{ process_null('st_agravo_aids') }}                                            AS st_agravo_aids,
            {{ process_null('st_agravo_alcolismo') }}                                       AS st_agravo_alcolismo,
            {{ process_null('st_agravo_diabete') }}                                         AS st_agravo_diabete,
            {{ process_null('st_agravo_drogas') }}                                          AS st_agravo_drogas,
            {{ process_null('st_agravo_mental') }}                                          AS st_agravo_mental,
            {{ process_null('st_agravo_outro') }}                                           AS st_agravo_outro,
            {{ process_null('st_agravo_tabaco') }}                                          AS st_agravo_tabaco,
            SAFE_CAST({{ process_null('st_agravo_tabagismo') }} AS INT64)                    AS st_agravo_tabagismo,
            {{ process_null('st_baciloscopia_1_mes') }}                                     AS st_baciloscopia_1_mes,
            {{ process_null('st_baciloscopia_2_mes') }}                                     AS st_baciloscopia_2_mes,
            {{ process_null('st_baciloscopia_3_mes') }}                                     AS st_baciloscopia_3_mes,
            {{ process_null('st_baciloscopia_4_mes') }}                                     AS st_baciloscopia_4_mes,
            {{ process_null('st_baciloscopia_5_mes') }}                                     AS st_baciloscopia_5_mes,
            {{ process_null('st_baciloscopia_6_mes') }}                                     AS st_baciloscopia_6_mes,
            {{ process_null('st_baciloscopia_escarro') }}                                   AS st_baciloscopia_escarro,
            {{ process_null('st_baciloscopia_escarro2') }}                                  AS st_baciloscopia_escarro2,
            {{ process_null('st_baciloscopia_outro') }}                                     AS st_baciloscopia_outro,
            {{ process_null('st_bacil_apos_6_mes') }}                                       AS st_bacil_apos_6_mes,
            {{ process_null('st_criptografia') }}                                           AS st_criptografia,
            {{ process_null('st_doenca_trabalho') }}                                        AS st_doenca_trabalho,
            {{ process_null('st_droga_estreptomicina') }}                                   AS st_droga_estreptomicina,
            {{ process_null('st_droga_etambutol') }}                                        AS st_droga_etambutol,
            {{ process_null('st_droga_etionamida') }}                                       AS st_droga_etionamida,
            {{ process_null('st_droga_isoniazida') }}                                       AS st_droga_isoniazida,
            {{ process_null('st_droga_outro') }}                                            AS st_droga_outro,
            {{ process_null('st_droga_pirazinamida') }}                                     AS st_droga_pirazinamida,
            {{ process_null('st_droga_rifampicina') }}                                      AS st_droga_rifampicina,
            {{ process_null('st_espelho') }}                                                AS st_espelho,
            {{ process_null('st_fluxo_retorno_recebido') }}                                  AS st_fluxo_retorno_recebido,
            {{ process_null('st_importado') }}                                              AS st_importado,
            {{ process_null('st_modo_transmissao') }}                                       AS st_modo_transmissao,
            SAFE_CAST({{ process_null('st_pcr_escarro') }} AS INT64)                         AS st_pcr_escarro,
            {{ process_null('st_vincula') }}                                                AS st_vincula,
            SAFE_CAST({{ process_null('timestamp') }} AS TIMESTAMP)                          AS timestamp,
            {{ process_null('tp_cpf') }}                                                    AS tp_cpf,
            {{ process_null('tp_antirretroviral_trat') }}                                   AS tp_antirretroviral_trat,
            {{ process_null('tp_autoctone_residencia') }}                                    AS tp_autoctone_residencia,
            {{ process_null('tp_benef_gov') }}                                              AS tp_benef_gov,
            {{ process_null('tp_classificacao_final') }}                                     AS tp_classificacao_final,
            {{ process_null('tp_criterio_confirmacao') }}                                    AS tp_criterio_confirmacao,
            {{ process_null('tp_cultura_escarro') }}                                        AS tp_cultura_escarro,
            {{ process_null('tp_cultura_justificativa') }}                                   AS tp_cultura_justificativa,
            {{ process_null('tp_cultura_outro') }}                                          AS tp_cultura_outro,
            {{ process_null('tp_delimitacao_surto') }}                                      AS tp_delimitacao_surto,
            {{ process_null('tp_duplicidade') }}                                            AS tp_duplicidade,
            {{ process_null('tp_entrada') }}                                                AS tp_entrada,
            {{ process_null('tp_escolaridade') }}                                           AS tp_escolaridade,
            {{ process_null('tp_evolucao_caso') }}                                          AS tp_evolucao_caso,
            {{ process_null('tp_extrapulmonar_1') }}                                        AS tp_extrapulmonar_1,
            {{ process_null('tp_extrapulmonar_2') }}                                        AS tp_extrapulmonar_2,
            {{ process_null('tp_fluxo_retorno') }}                                          AS tp_fluxo_retorno,
            {{ process_null('tp_forma') }}                                                  AS tp_forma,
            {{ process_null('tp_gestante') }}                                               AS tp_gestante,
            {{ process_null('tp_histopatologia') }}                                         AS tp_histopatologia,
            {{ process_null('tp_hiv') }}                                                    AS tp_hiv,
            {{ process_null('tp_inquerito') }}                                              AS tp_inquerito,
            {{ process_null('tp_institucionalizado') }}                                     AS tp_institucionalizado,
            {{ process_null('tp_local_infeccao') }}                                         AS tp_local_infeccao,
            {{ process_null('tp_local_surto') }}                                            AS tp_local_surto,
            {{ process_null('tp_modo_infeccao') }}                                          AS tp_modo_infeccao,
            {{ process_null('tp_molecular') }}                                              AS tp_molecular,
            {{ process_null('tp_notificacao') }}                                            AS tp_notificacao,
            {{ process_null('tp_pcr_escarro') }}                                            AS tp_pcr_escarro,
            {{ process_null('tp_pop_imigrante') }}                                          AS tp_pop_imigrante,
            {{ process_null('tp_pop_liberdade') }}                                          AS tp_pop_liberdade,
            {{ process_null('tp_pop_saude') }}                                              AS tp_pop_saude,
            {{ process_null('tp_pop_rua') }}                                                AS tp_pop_rua,
            {{ process_null('tp_raca_cor') }}                                               AS tp_raca_cor,
            {{ process_null('tp_raio_x') }}                                                 AS tp_raio_x,
            {{ process_null('tp_sensibilidade') }}                                          AS tp_sensibilidade,
            {{ process_null('tp_sexo') }}                                                   AS tp_sexo,
            {{ process_null('tp_sistema') }}                                                AS tp_sistema,
            {{ process_null('tp_situacao_encerramento') }}                                   AS tp_situacao_encerramento,
            {{ process_null('tp_situacao_mes_12') }}                                        AS tp_situacao_mes_12,
            {{ process_null('tp_situacao_mes_9') }}                                         AS tp_situacao_mes_9,
            {{ process_null('tp_suspeita') }}                                               AS tp_suspeita,
            {{ process_null('tp_transf') }}                                                 AS tp_transf,
            {{ process_null('tp_tratamento') }}                                             AS tp_tratamento,
            {{ process_null('tp_tratamento_acompanhamento') }}                               AS tp_tratamento_acompanhamento,
            {{ process_null('tp_turberculinico') }}                                         AS tp_turberculinico,
            {{ process_null('tp_veiculo_transmissao') }}                                     AS tp_veiculo_transmissao,
            {{ process_null('tp_zona_residencia') }}                                        AS tp_zona_residencia,
            {{ process_null('ts_codigo1') }}                                                AS ts_codigo1,
            {{ process_null('ts_codigo2') }}                                                AS ts_codigo2,
            {{ process_null('inv_unidade') }}                                               AS inv_unidade,
            {{ process_null('inv_cod_unidade') }}                                           AS inv_cod_unidade,
            SAFE_CAST({{ process_null('inv_id_user') }} AS INT64)                            AS inv_id_user,
            {{ process_null('inv_nome') }}                                                  AS inv_nome,
            {{ process_null('inv_funcao') }}                                                AS inv_funcao,
            SAFE_CAST({{ process_null('visivel') }} AS INT64)                                AS visivel,
            {{ process_null('equipe') }}                                                    AS equipe,
            {{ process_null('unidade_res') }}                                               AS unidade_res,
            {{ process_null('resp_encerramento') }}                                         AS resp_encerramento,
            SAFE_CAST({{ process_null('tp_unidad_notificadora_externa') }} AS NUMERIC)       AS tp_unidad_notificadora_externa,
            {{ process_null('co_unidad_notificadora_externa') }}                             AS co_unidad_notificadora_externa,

            safe_cast({{ process_null('datalake_loaded_at') }} as timestamp) as datalake_loaded_at
        from sem_duplicatas
    )
select * from extrair_informacoes
