# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "rj_sms"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Defining variables
vars:
  # Internal variables
  DBT_USER: "{{ env_var('DBT_USER', 'dev_fantasma') }}"
  
  # Policy tags
  #  Free access:
  TAG_PUBLICO_CPF: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/5699415336157868746'
  TAG_PUBLICO_CNS: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/7387549036507982422'
  TAG_PUBLICO_CONSELHO_DE_CLASSE: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/8947953670499880401'
  TAG_PUBLICO_DATA_NASCIMENTO: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/1089827107712020997'
  TAG_PUBLICO_IDENTIDADE: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/3743809371220572672'
  TAG_PUBLICO_IDENTIFICADOR_SISTEMA: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/1209329132431056760'
  TAG_PUBLICO_NOME: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/9103837752323511776'
  TAG_PUBLICO_NOME_MAE: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/8561050879085790814'
  TAG_PUBLICO_NOME_PAI: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/4885144376878158083'
  TAG_PUBLICO_OUTRO_DOC: 'projects/rj-sms/locations/us/taxonomies/6081774755636705541/policyTags/4320640137660013492'

  #  Restricted access:
  #   Identifiers
  TAG_CPF: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/1689671600024046932'
  TAG_CNS: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/2901367901059215729'
  TAG_CONSELHO_DE_CLASSE: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/4548538642730180995'
  TAG_DATA_NASCIMENTO: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/8548247179869888647'
  #TAG_DATA_OBITO: ''
  TAG_IDENTIDADE: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/8263914069321607924'
  TAG_IDENTIFICADOR_SISTEMA: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/7573439620630018034'
  TAG_NOME: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/5037947799828588462'
  TAG_NOME_MAE: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/3410377021813867603'
  TAG_NOME_PAI: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/1248058356263361805'
  TAG_OUTRO_DOC: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/7339421740683120932'
  #   Other information:
  TAG_CONTATO: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/5804345045751147976'
  TAG_EMAIL: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/1724143358615811174'
  TAG_ENDERECO: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/3861022792882552590'
  TAG_TELEFONE: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/6732688311195525698'
  TAG_DADO_BANCARIO: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/4150697899389182141'
  TAG_DADO_CLINICO: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/7155330191381842548'
  TAG_DADO_ESTOQUE: 'projects/rj-sms/locations/us/taxonomies/8150870731612680617/policyTags/9217789274924499899'


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +persist_docs:
    relation: true
    columns: true
  elementary:
    +schema: "gerenciamento__dbt_elementary"
    +enabled: "{{ target.name in ['prod'] }}"
  rj_sms:
    # all models should have unique and not null
    +required_tests: { "unique.*|not_null": 2 }
    +required_docs: true
    raw:
      +materialized: table
      +tags: "raw"
      cnes_web:
        +schema: brutos_cnes_web
        +tags: "weekly"
        +labels:
          dado_publico: sim
          dado_pessoal: sim
          dado_sensivel: nao
      cnes_ftp:
        +schema: brutos_cnes_ftp
        +tags: "weekly"
        +labels:
          dado_publico: sim
          dado_pessoal: sim
          dado_sensivel: nao
      ergon:
        +schema: brutos_ergon
        +tags: ["daily", "ergon"]
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_sensivel: sim
      conectividade:
        +schema: brutos_conectividade
        +tags: ["daily"]
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_sensivel: nao
      datasus:
        +schema: brutos_datasus
        +tags: "weekly"
        +labels:
          dado_publico: sim
          dado_pessoal: sim
          dado_sensivel: nao
      monitoramento:
        +schema: gerenciamento__historico_clinico__logs
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_sensivel: nao
      estoque_central_tpc:
        +schema: brutos_estoque_central_tpc
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_sensivel: nao
          dominio: estoque
      historico_clinico_integrado:
        +schema: brutos_historico_clinico_integrado
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_sensivel: sim
          dominio: historico_clinico
      plataforma_smsrio:
        +schema: brutos_plataforma_smsrio
        +tags: ["smsrio", "daily"]
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_sensivel: sim
      plataforma_clickup:
        +schema: brutos_plataforma_clickup
        +tags: ["daily"]
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_sensivel: sim
      prontuario_vitacare:
        +schema: brutos_prontuario_vitacare
        +tags: ["vitacare", "daily"]
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_sensivel: sim
          dominio: historico_clinico
      prontuario_vitai:
        +schema: brutos_prontuario_vitai
        +tags: "vitai"
        +labels:
          dado_publico: nao
          dado_pessoal: sim
          dado_sensivel: sim
          dominio: historico_clinico
      osinfo:
        +schema: brutos_osinfo
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_sensivel: nao
      sheets:
        +schema: brutos_sheets
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_sensivel: nao
      sih:
        +schema: brutos_sih
        +tags: "daily"
        +labels:
          dado_publico: nao
          dado_pessoal: nao
          dado_sensivel: nao
    intermediate:
      +materialized: ephemeral
      dit:
        historico_clinico:
          +tags: ["hci", "daily"]
          +labels:
            dado_publico: nao
            dado_pessoal: sim
            dado_sensivel: sim
            dominio: historico_clinico
          paciente:
            +tags: ["paciente"]
        monitoramento:
          +tags: "daily"
          +labels:
            dado_publico: nao
            dado_pessoal: nao
            dado_sensivel: nao
    marts:
      +materialized: table
      core:
        +tags: "core"
        dimensions:
          +schema: saude_dados_mestres
          +labels:
            dado_publico: nao
            dado_pessoal: nao
            dado_sensivel: nao
          rio:
            +schema: saude_rio
            +tags: "weekly"
            +labels:
              dado_publico: sim
              dado_pessoal: sim
              dado_sensivel: nao
        facts:
          sisreg:
            +schema: saude_sisreg
            +tags: "daily"
            +labels:
              dado_publico: nao
              dado_pessoal: nao
              dado_sensivel: nao
          estoque:
            +schema: saude_estoque
            +tags: "daily"
            +labels:
              dado_publico: nao
              dado_pessoal: sim
              dado_sensivel: sim
              dominio: estoque
      subgeral:
        cnes:
          +schema: projeto_cnes_subgeral
          +tags: ["weekly", "subgeral", "cnes_subgeral"]
          +labels:
            dado_publico: nao
            dado_pessoal: sim
            dado_sensivel: sim
            dominio: subgeral
        monitora_reg:
          +schema: projeto_monitora_reg
          +tags: ["weekly", "subgeral", "monitora_reg"]
          +labels:
            dado_publico: naos
            dado_pessoal: sim
            dado_sensivel: nao
            dominio: subgeral
        sisreg_reports:
          +schema: projeto_sisreg_reports
          +tags: ["weekly", "subgeral", "sisreg_reports"]
          +labels:
            dado_publico: nao
            dado_pessoal: sim
            dado_sensivel: nao
            dominio: subgeral

      dit:
        dengue:
          +schema: projeto_dengue
          +tags: "daily"
        estoque:
          +schema: projeto_estoque
          +tags: ["daily", "estoque"]
          +labels:
            dado_publico: nao
            dado_pessoal: sim
            dado_sensivel: sim
            dominio: estoque
        gerenciamento:
          +tags: "daily"
        historico_clinico:
          +tags: ["daily", "hci"]
          +labels:
            dado_publico: nao
            dado_pessoal: sim
            dado_sensivel: sim
            dominio: historico_clinico
        historico_clinico_app:
          +tags: ["daily", "hci_app"]
          +labels:
            dado_publico: nao
            dado_pessoal: sim
            dado_sensivel: sim
            dominio: historico_clinico_app
    staging:
      +materialized: table
      +tags: ["staging"]
      prontuario_vitacare:
        +schema: brutos_prontuario_vitacare_staging
      prontuario_vitai:
        +schema: brutos_prontuario_vitai_staging
      plataforma_smsrio:
        +schema: brutos_plataforma_smsrio_staging
      estoque_central_tpc:
        +schema: brutos_estoque_central_tpc_staging
tests:
  rj_sms:
    +severity: error
    +store_failures: true
    +schema: gerenciamento__dbt_test_audit

seeds:
  rj_sms:

flags:
  require_explicit_package_overrides_for_builtin_materializations: False
  source_freshness_run_project_hooks: True
