default:
  target: prodlocal
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: dbt
      location: US
      threads: 20
      keyfile: /tmp/credentials.json
    prod:
      type: bigquery
      method: service-account
      project: rj-sms
      dataset: dbt
      location: US
      threads: 20
      keyfile: /tmp/credentials.json
    devlocal:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: dbt
      location: US
      threads: 20
      keyfile: /home/danilo/.credentials/rj-sms-dev-a8fd4239a9eb.json
    prodlocal:
      type: bigquery
      method: service-account
      project: rj-sms
      dataset: dbt
      location: US
      threads: 20
      keyfile: /home/danilo/.credentials/rj-sms-f0dc62a2b7d5.json
    compile:
      type: bigquery
      method: service-account
      project: rj-sms-dev
      dataset: dbt
      location: US
      threads: 20
      keyfile: credentials/dev.json
