version: 2

models :
  - name: my_second_dbt_model
    description: "**Descrição**: example\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: example\n**Órgão gestor dos dados**: example\n**Publicado por**:\
      \ example\n**Publicado por (email)**: example@gmail.com\n"
    columns:
      - name: id
        description: The primary key for this table
  - name: my_first_dbt_model
    description: "**Descrição**: example\n**Frequência de atualização**: Nunca\n**Cobertura\
      \ temporal**: example\n**Órgão gestor dos dados**: example\n**Publicado por**:\
      \ example\n**Publicado por (email)**: example@gmail.com\n"
    columns:
      - name: id
        description: The primary key for this table
