{{
    config(
        schema="brutos_sih_staging",
        alias="indicadores_hospitalares",
    )
}}

with source as (
      select * from {{ source('brutos_sih_staging', 'indicadores_hospitalares') }}
),
renamed as (
    select
        {{ adapter.quote("uf_zi") }},
        {{ adapter.quote("ano_cmpt") }},
        {{ adapter.quote("mes_cmpt") }},
        {{ adapter.quote("espec") }},
        {{ adapter.quote("cgc_hosp") }},
        {{ adapter.quote("n_aih") }},
        {{ adapter.quote("ident") }},
        {{ adapter.quote("cep") }},
        {{ adapter.quote("munic_res") }},
        {{ adapter.quote("nasc") }},
        {{ adapter.quote("sexo") }},
        {{ adapter.quote("uti_mes_in") }},
        {{ adapter.quote("uti_mes_an") }},
        {{ adapter.quote("uti_mes_al") }},
        {{ adapter.quote("uti_mes_to") }},
        {{ adapter.quote("marca_uti") }},
        {{ adapter.quote("uti_int_in") }},
        {{ adapter.quote("uti_int_an") }},
        {{ adapter.quote("uti_int_al") }},
        {{ adapter.quote("uti_int_to") }},
        {{ adapter.quote("diar_acom") }},
        {{ adapter.quote("qt_diarias") }},
        {{ adapter.quote("proc_solic") }},
        {{ adapter.quote("proc_rea") }},
        {{ adapter.quote("val_sh") }},
        {{ adapter.quote("val_sp") }},
        {{ adapter.quote("val_sadt") }},
        {{ adapter.quote("val_rn") }},
        {{ adapter.quote("val_acomp") }},
        {{ adapter.quote("val_ortp") }},
        {{ adapter.quote("val_sangue") }},
        {{ adapter.quote("val_sadtsr") }},
        {{ adapter.quote("val_transp") }},
        {{ adapter.quote("val_obsang") }},
        {{ adapter.quote("val_ped1ac") }},
        {{ adapter.quote("val_tot") }},
        {{ adapter.quote("val_uti") }},
        {{ adapter.quote("us_tot") }},
        parse_date('%Y%m%d', dt_inter) as dt_inter,
        parse_date('%Y%m%d', dt_saida) as dt_saida,
        {{ adapter.quote("diag_princ") }},
        {{ adapter.quote("diag_secun") }},
        {{ adapter.quote("cobranca") }},
        {{ adapter.quote("natureza") }},
        {{ adapter.quote("nat_jur") }},
        {{ adapter.quote("gestao") }},
        {{ adapter.quote("rubrica") }},
        {{ adapter.quote("ind_vdrl") }},
        {{ adapter.quote("munic_mov") }},
        {{ adapter.quote("cod_idade") }},
        {{ adapter.quote("idade") }},
        {{ adapter.quote("dias_perm") }},
        {{ adapter.quote("morte") }},
        {{ adapter.quote("nacional") }},
        {{ adapter.quote("num_proc") }},
        {{ adapter.quote("car_int") }},
        {{ adapter.quote("tot_pt_sp") }},
        {{ adapter.quote("cpf_aut") }},
        {{ adapter.quote("homonimo") }},
        {{ adapter.quote("num_filhos") }},
        {{ adapter.quote("instru") }},
        {{ adapter.quote("cid_notif") }},
        {{ adapter.quote("contracep1") }},
        {{ adapter.quote("contracep2") }},
        {{ adapter.quote("gestrisco") }},
        {{ adapter.quote("insc_pn") }},
        {{ adapter.quote("seq_aih5") }},
        {{ adapter.quote("cbor") }},
        {{ adapter.quote("cnaer") }},
        {{ adapter.quote("vincprev") }},
        {{ adapter.quote("gestor_cod") }},
        {{ adapter.quote("gestor_tp") }},
        {{ adapter.quote("gestor_cpf") }},
        {{ adapter.quote("gestor_dt") }},
        {{ adapter.quote("cnes") }},
        {{ adapter.quote("cnpj_mant") }},
        {{ adapter.quote("infehosp") }},
        {{ adapter.quote("cid_asso") }},
        {{ adapter.quote("cid_morte") }},
        {{ adapter.quote("complex") }},
        {{ adapter.quote("financ") }},
        {{ adapter.quote("faec_tp") }},
        {{ adapter.quote("regct") }},
        {{ adapter.quote("raca_cor") }},
        {{ adapter.quote("etnia") }},
        {{ adapter.quote("sequencia") }},
        {{ adapter.quote("remessa") }},
        {{ adapter.quote("aud_just") }},
        {{ adapter.quote("sis_just") }},
        {{ adapter.quote("val_sh_fed") }},
        {{ adapter.quote("val_sp_fed") }},
        {{ adapter.quote("val_sh_ges") }},
        {{ adapter.quote("val_sp_ges") }},
        {{ adapter.quote("val_uci") }},
        {{ adapter.quote("marca_uci") }},
        {{ adapter.quote("diagsec1") }},
        {{ adapter.quote("diagsec2") }},
        {{ adapter.quote("diagsec3") }},
        {{ adapter.quote("diagsec4") }},
        {{ adapter.quote("diagsec5") }},
        {{ adapter.quote("diagsec6") }},
        {{ adapter.quote("diagsec7") }},
        {{ adapter.quote("diagsec8") }},
        {{ adapter.quote("diagsec9") }},
        {{ adapter.quote("tpdisec1") }},
        {{ adapter.quote("tpdisec2") }},
        {{ adapter.quote("tpdisec3") }},
        {{ adapter.quote("tpdisec4") }},
        {{ adapter.quote("tpdisec5") }},
        {{ adapter.quote("tpdisec6") }},
        {{ adapter.quote("tpdisec7") }},
        {{ adapter.quote("tpdisec8") }},
        {{ adapter.quote("tpdisec9") }},
        {{ adapter.quote("_data_carga") }},
        {{ adapter.quote("ano_particao") }},
        {{ adapter.quote("mes_particao") }},
        {{ adapter.quote("data_particao") }}

    from source
)
select * from renamed
  