{{ config(
    alias="pre_natal",
    schema="brutos_prontuario_vitacare_api",
    materialized="incremental",
    incremental_strategy="insert_overwrite",
    partition_by={"field": "data_particao", "data_type": "date", "granularity": "day"}
) }}

{% set last_30_days = (
    "date_sub(current_date('America/Sao_Paulo'), interval 30 day)"
) %}

WITH bruto_atendimento AS (
  SELECT

    CONCAT(NULLIF(payload_cnes, ''), '.', NULLIF(source_id, '')) AS id_prontuario_global,
    CAST(source_id AS STRING) AS id_prontuario_local,
    CAST(payload_cnes AS STRING) AS id_cnes,

    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].param_peso') AS NUMERIC) AS param_peso,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].param_tamin') AS NUMERIC) AS param_tamin,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].param_tamax') AS NUMERIC) AS param_tamax,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].consseguintes_afu') AS NUMERIC) AS consseguintes_afu,

    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].edema') AS edema,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].observacoes') AS observacoes,

    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_peso_habitual') AS NUMERIC) AS pconsulta_peso_habitual,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_altura') AS NUMERIC) AS pconsulta_altura,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_idade_gestacional') AS NUMERIC) AS pconsulta_idade_gestacional,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].grupo_sanguineo_gravida') AS grupo_sanguineo_gravida,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_grupo_sanguineo_pai') AS pconsulta_grupo_sanguineo_pai,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].consseguintes_afuobs') AS consseguintes_afuobs,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pelvimetria_clinica') AS pelvimetria_clinica,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].agraval_risco_prenatal_histo_reprod') AS agraval_risco_prenatal_histo_reprod,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].agraval_risco_prenatal_histo_obstet_anterior') AS agraval_risco_prenatal_histo_obstet_anterior,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].agraval_risco_prenatal_patol_associada') AS agraval_risco_prenatal_patol_associada,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].agraval_risco_prenatal_gravidez_actual') AS agraval_risco_prenatal_gravidez_actual,

    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].aval_risco_prenatal_total_indices') AS NUMERIC) AS aval_risco_prenatal_total_indices,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].agraval_risco_prenatal_escala_nunomont') AS agraval_risco_prenatal_escala_nunomont,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_glicemia_pos_50') AS NUMERIC) AS exames_lab_glicemia_pos_50,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_tcoombs') AS exames_lab_tcoombs,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_glicemia_jejum') AS NUMERIC) AS exames_lab_glicemia_jejum,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_ptgo_0') AS NUMERIC) AS exames_lab_ptgo_0,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_ptgo_60') AS NUMERIC) AS exames_lab_ptgo_60,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_ptg_120') AS NUMERIC) AS exames_lab_ptg_120,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_ptg_180') AS NUMERIC) AS exames_lab_ptg_180,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_creatinemia') AS NUMERIC) AS exames_lab_creatinemia,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_vdrl') AS exames_lab_vdrl,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_toxoplasmose_imun') AS exames_lab_toxoplasmose_imun,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_rubeola_igg') AS NUMERIC) AS exames_lab_rubeola_igg,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_rubeola_igm') AS NUMERIC) AS exames_lab_rubeola_igm,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_rubeola_imun') AS exames_lab_rubeola_imun,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_aghbs') AS NUMERIC) AS exames_lab_aghbs,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_hiv') AS exames_lab_hiv,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_urocultura') AS exames_lab_urocultura,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_urocultura_positiva') AS exames_lab_urocultura_positiva,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_clinic_mama_esq_inspeccao') AS exame_clinic_mama_esq_inspeccao,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_clini_cmama_esq_palpacao') AS exame_clini_cmama_esq_palpacao,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_clinic_mama_dir_inspeccao') AS exame_clinic_mama_dir_inspeccao,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_clinic_mama_dir_palpacao') AS exame_clinic_mama_dir_palpacao,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_ginec_vulva_vagina') AS exame_ginec_vulva_vagina,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].colo_utero_exame') AS colo_utero_exame,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].colo_utero_toque') AS colo_utero_toque,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_citologiares') AS exame_citologiares,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_dum1') AS NUMERIC) AS pconsulta_dum1,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_dpp1') AS pconsulta_dpp1,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].agraval_risco_prenatal_obs') AS agraval_risco_prenatal_obs,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_idade_gestacional_dias') AS NUMERIC) AS pconsulta_idade_gestacional_dias,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_clinic_mama_esq_inspeccao_obs') AS exame_clinic_mama_esq_inspeccao_obs,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_clinic_mama_dir_inspeccao_obs') AS exame_clinic_mama_dir_inspeccao_obs,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_clinic_mama_esq_palpacao_obs') AS exame_clinic_mama_esq_palpacao_obs,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_clinic_mama_dir_palpacao_obs') AS exame_clinic_mama_dir_palpacao_obs,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].queixas_mam') AS queixas_mam,

    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_eritrocitos') AS NUMERIC) AS analises_eritrocitos,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_hemoglobina') AS NUMERIC) AS analises_hemoglobina,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_hematocrito') AS NUMERIC) AS analises_hematocrito,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_gm') AS NUMERIC) AS analises_gm,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_hgm') AS NUMERIC) AS analises_hgm,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_chgm') AS NUMERIC) AS analises_chgm,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_leucocitos') AS NUMERIC) AS analises_leucocitos,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_neutrifilos') AS NUMERIC) AS analises_neutrifilos,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_eosinofilos') AS NUMERIC) AS analises_eosinofilos,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_basofilos') AS NUMERIC) AS analises_basofilos,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_linfocitos') AS NUMERIC) AS analises_linfocitos,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_monocitos') AS NUMERIC) AS analises_monocitos,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_plaquetas') AS NUMERIC) AS cseguintes_alalises_plaquetas,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_acidourico') AS NUMERIC) AS cseguintes_alalises_acidourico,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_citomegalo_virus') AS cseguintes_alalises_citomegalo_virus,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_achbs') AS NUMERIC) AS cseguintes_alalises_achbs,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_achbc') AS NUMERIC) AS cseguintes_alalises_achbc,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_achvc') AS NUMERIC) AS cseguintes_alalises_achvc,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_alfa_proteina') AS NUMERIC) AS cseguintes_alalises_alfa_proteina,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_inibinaa') AS NUMERIC) AS cseguintes_alalises_inibinaa,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_estradiol') AS NUMERIC) AS cseguintes_alalises_estradiol,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_hormona_beta_corionica') AS NUMERIC) AS cseguintes_alalises_hormona_beta_corionica,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_tempo_protrombina') AS NUMERIC) AS cseguintes_alalises_tempo_protrombina,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_ttrombo_plastina_parcial') AS NUMERIC) AS cseguintes_alalises_ttrombo_plastina_parcial,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_alalises_ecografia_obstetrica') AS cseguintes_alalises_ecografia_obstetrica,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].alalises_eco_obstet_morfologica') AS alalises_eco_obstet_morfologica,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_citologia_resrccu') AS exame_citologia_resrccu,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_dum1dias') AS NUMERIC) AS pconsulta_dum1dias,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].data_mamografia') AS data_mamografia,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].res_mamografias') AS res_mamografias,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_combur') AS analises_combur_combur,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_bilirrubina') AS analises_combur_bilirrubina,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_urobilogenio') AS analises_combur_urobilogenio,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_cetonas') AS analises_combur_cetonas,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_glucose') AS analises_combur_glucose,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_proteinas') AS analises_combur_proteinas,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_sangue') AS analises_combur_sangue,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_nitritos') AS analises_combur_nitritos,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_ph') AS analises_combur_ph,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_densidade') AS analises_combur_densidade,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].analises_combur_leucocitos') AS analises_combur_leucocitos,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_urocultur_ancolonias') AS exames_lab_urocultur_ancolonias,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].data_resultado_citologia') AS data_resultado_citologia,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_tamax') AS NUMERIC) AS pconsulta_tamax,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].pconsulta_tamin') AS NUMERIC) AS pconsulta_tamin,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].dta_eco') AS dta_eco,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].res_mamografias_obs') AS res_mamografias_obs,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cons_seguintes_perimetro_abdominal') AS NUMERIC) AS cons_seguintes_perimetro_abdominal,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].primeira_consulta_idade_gestacional') AS NUMERIC) AS primeira_consulta_idade_gestacional,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].primeira_consulta_idade_gestacional_dias') AS NUMERIC) AS primeira_consulta_idade_gestacional_dias,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].res_exames_lab_toxoplasmose_igg') AS res_exames_lab_toxoplasmose_igg,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].res_exames_lab_toxoplasmose_igm') AS res_exames_lab_toxoplasmose_igm,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_cultura_ag_patologicos') AS exames_lab_cultura_ag_patologicos,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_cultura_tsa_sensiveis') AS exames_lab_cultura_tsa_sensiveis,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_cultura_tsa_resistentes') AS exames_lab_cultura_tsa_resistentes,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exame_ginec_vulva_vagina_outras') AS exame_ginec_vulva_vagina_outras,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].colo_utero_toque_outras') AS colo_utero_toque_outras,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].classificacao_gestacao_alto_risco') AS classificacao_gestacao_alto_risco,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].gestante_gestacoes_num') AS NUMERIC) AS gestante_gestacoes_num,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_tratamento_dose_1') AS sifilis_tratamento_dose_1,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_tratamento_dose_2') AS sifilis_tratamento_dose_2,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_tratamento_dose_3') AS sifilis_tratamento_dose_3,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_tratamento_de_parceiro') AS sifilis_tratamento_de_parceiro,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_inc_ou_efetuado_tratamento_parceiro_dose_1') AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_1,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_inc_ou_efetuado_tratamento_parceiro_dose_2') AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_2,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_inc_ou_efetuado_tratamento_parceiro_dose_3') AS sifilis_inc_ou_efetuado_tratamento_parceiro_dose_3,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_data_visita_domiciliar') AS sifilis_data_visita_domiciliar,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_motivo_visita_domiciliar') AS sifilis_motivo_visita_domiciliar,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_observacoes') AS sifilis_observacoes,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_streptoccus_b') AS exames_lab_streptoccus_b,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_streptoccus_b_obs') AS exames_lab_streptoccus_b_obs,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].consulta_seguintes_intercorrencias') AS consulta_seguintes_intercorrencias,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_hemoglobina_d') AS NUMERIC) AS exames_lab_hemoglobina_d,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_vdrl_titulacao') AS exames_lab_vdrl_titulacao,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_teste_rapido_sifilis_parceiro') AS sifilis_teste_rapido_sifilis_parceiro,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_vdrl_parceiro') AS sifilis_vdrl_parceiro,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cons_seguintes_placenta_posicionamento') AS cons_seguintes_placenta_posicionamento,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cons_seguintes_placenta_sinais_risco') AS cons_seguintes_placenta_sinais_risco,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cons_seguintes_placenta_maturidade') AS cons_seguintes_placenta_maturidade,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cons_seguintes_placenta_observacoes') AS cons_seguintes_placenta_observacoes,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cons_seguintes_liquido_amniotico') AS cons_seguintes_liquido_amniotico,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cons_seguintes_liquido_amniotico_observacoes') AS cons_seguintes_liquido_amniotico_observacoes,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].cseguintes_cardiotocografia') AS cseguintes_cardiotocografia,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_titulacao_parceiro') AS sifilis_titulacao_parceiro,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].sifilis_esquema_tratamento_parceiro') AS sifilis_esquema_tratamento_parceiro,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_agr_testes_rapidos_hiv') AS exames_lab_agr_testes_rapidos_hiv,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].exames_lab_agr_testes_rapidos_hiv_positivo') AS exames_lab_agr_testes_rapidos_hiv_positivo,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smrpuerperiodata') AS smrpuerperiodata,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smlocalparto') AS smlocalparto,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smtipoparto') AS smtipoparto,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smresivaopuerpobs') AS smresivaopuerpobs,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioparametrospeso') AS NUMERIC) AS smpuerperioparametrospeso,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioparametrostamin') AS NUMERIC) AS smpuerperioparametrostamin,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioparametrostamax') AS NUMERIC) AS smpuerperioparametrostamax,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperiocitologia') AS smpuerperiocitologia,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioalalisesplaquetas') AS NUMERIC) AS smpuerperioalalisesplaquetas,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioalalisesglicemia') AS NUMERIC) AS smpuerperioalalisesglicemia,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioalalisescreatinina') AS NUMERIC) AS smpuerperioalalisescreatinina,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioalalisesgamagt') AS NUMERIC) AS smpuerperioalalisesgamagt,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioalalisesgot') AS NUMERIC) AS smpuerperioalalisesgot,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioalalisesgtp') AS NUMERIC) AS smpuerperioalalisesgtp,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioalalisesbilirrubinas') AS smpuerperioalalisesbilirrubinas,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperioalaliseacidourico') AS NUMERIC) AS smpuerperioalaliseacidourico,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].smpuerperiourocultura') AS smpuerperiourocultura,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].classificacaotipoparto') AS classificacaotipoparto,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiomcdtsfosfatasealcalina') AS NUMERIC) AS puerperiomcdtsfosfatasealcalina,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiomcdtsurinai') AS puerperiomcdtsurinai,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiomcdtsurinaiobs') AS puerperiomcdtsurinaiobs,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiourocultura') AS puerperiourocultura,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperionumcolonias') AS puerperionumcolonias,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperioagentespatologicos') AS puerperioagentespatologicos,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiotsasensiveis') AS puerperiotsasensiveis,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiotsaresistentes') AS puerperiotsaresistentes,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiomcdtsurinairesulltado') AS puerperiomcdtsurinairesulltado,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiotermo') AS puerperiotermo,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiorazaocesareo') AS puerperiorazaocesareo,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiorh') AS puerperiorh,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiogamaglobulinaantid') AS puerperiogamaglobulinaantid,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiogamaglobulinaantiddata') AS puerperiogamaglobulinaantiddata,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].gestantepuerperionumrecemnascidos') AS NUMERIC) AS gestantepuerperionumrecemnascidos,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].gestantepuerperioamamentacao') AS gestantepuerperioamamentacao,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiodataaborto') AS puerperiodataaborto,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiotipoaborto') AS puerperiotipoaborto,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperioidadegestacao') AS NUMERIC) AS puerperioidadegestacao,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].gestantepuerperiocuretagem') AS gestantepuerperiocuretagem,
    JSON_EXTRACT_SCALAR(data, '$.pre_natal[0].puerperiooutrotermoqual') AS puerperiooutrotermoqual,

    SAFE_CAST(datalake_loaded_at AS DATETIME) AS loaded_at,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.datahora_fim_atendimento') AS DATE) AS data_particao,
    
  FROM {{ source("brutos_prontuario_vitacare_staging_dev", "atendimento_continuo") }}
  WHERE JSON_EXTRACT(data, '$.pre_natal') IS NOT NULL
  AND JSON_EXTRACT(data, '$.pre_natal') != '[]'

  {% if is_incremental() %}
    AND DATE(SAFE_CAST(datalake_loaded_at AS TIMESTAMP), 'America/Sao_Paulo') >= {{ last_30_days }}
  {% endif %}

  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY id_prontuario_global
    ORDER BY loaded_at DESC
  ) = 1
)

SELECT * FROM bruto_atendimento