{{ config(
    alias="idoso",
    materialized="incremental",
    schema="brutos_prontuario_vitacare_api",
    incremental_strategy="insert_overwrite",
    partition_by={"field": "data_particao", "data_type": "date", "granularity": "day"}
) }}

{% set last_partition = get_last_partition_date(this) %}

WITH bruto_atendimento AS (
  SELECT
    CAST(source_id AS STRING) AS id_prontuario_local,
    CONCAT(NULLIF(CAST(payload_cnes AS STRING), ''), '.', NULLIF(CAST(source_id AS STRING), '')) AS id_prontuario_global,
    CAST(payload_cnes AS STRING) AS id_cnes,
    SAFE_CAST(datalake_loaded_at AS DATETIME) AS loaded_at,
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.datahora_fim_atendimento') AS DATETIME) AS datahora_fim_atendimento,
    SAFE.PARSE_JSON(data) AS json_data,
    DATE(COALESCE(SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.datahora_fim_atendimento') AS DATETIME), SAFE_CAST(datalake_loaded_at AS DATETIME))) AS data_particao
  FROM {{ source("brutos_prontuario_vitacare_staging_dev", "atendimento_continuo") }}
  WHERE JSON_EXTRACT(data, '$.idoso') IS NOT NULL
  AND JSON_EXTRACT(data, '$.idoso') != '[]'
  {% if is_incremental() %}
    AND DATE(datalake_loaded_at, 'America/Sao_Paulo') >= DATE('{{ last_partition }}')
  {% endif %}
  qualify row_number() over (partition by id_prontuario_global order by loaded_at desc) = 1
),

idoso_extraido AS (
  SELECT
    id_prontuario_global,
    id_prontuario_local,
    id_cnes,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelAlimentacao')        AS dep_barthel_alimentacao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelBanho')              AS dep_barthel_banho,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelHigienePessoal')     AS dep_barthel_higiene_pessoal,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelVestirse')           AS dep_barthel_vestirse,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelControloAnal')       AS dep_barthel_controlo_anal,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelControloVesical')    AS dep_barthel_controlo_vesical,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelUtilizacaoSanita')   AS dep_barthel_utilizacao_sanita,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelTransferencia')      AS dep_barthel_transferencia,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelMobilidade')         AS dep_barthel_mobilidade,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelEscadas')            AS dep_barthel_escadas,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depBarthelTotal')              AS dep_barthel_total,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoAno')          AS dep_mms_orientacao_ano,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoMes')          AS dep_mms_orientacao_mes,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoDiaMes')       AS dep_mms_orientacao_dia_mes,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoDiaSeman')     AS dep_mms_orientacao_dia_seman,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsLinguagemARelogio')      AS dep_mms_linguagem_arelogio,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsLinguagemC1')            AS dep_mms_linguagem_c1,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsLinguagemC2')            AS dep_mms_linguagem_c2,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsLinguagemC3')            AS dep_mms_linguagem_c3,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsLinguagemDOlhos')        AS dep_mms_linguagem_dolhos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsLinguagemEFrase')        AS dep_mms_linguagem_efrase,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsHabilidadeDesenho')      AS dep_mms_habilidade_desenho,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsPontosP')                AS dep_mms_pontos_p,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depObservacoes')               AS dep_observacoes,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsConclusao') AS dep_mms_conclusao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsRetencaoCaneca') AS dep_mms_retencao_caneca,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsRetencaoTijolo') AS dep_mms_retencao_tijolo,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsRetencaoTapete') AS dep_mms_retencao_tapete,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoSemestre') AS dep_mms_orientacao_semestre,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoEstado') AS dep_mms_orientacao_estado,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoCidade') AS dep_mms_orientacao_cidade,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoBairro') AS dep_mms_orientacao_bairro,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoRua') AS dep_mms_orientacao_rua,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsOrientacaoLocal') AS dep_mms_orientacao_local,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculoAval') AS dep_mms_calculo_aval,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculo93') AS dep_mms_calculo_93,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculo86') AS dep_mms_calculo_86,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculo79') AS dep_mms_calculo_79,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculo72') AS dep_mms_calculo_72,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculo65') AS dep_mms_calculo_65,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsMemorizacaoCaneca') AS dep_mms_memorizacao_caneca,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsMemorizacaoTijolo') AS dep_mms_memorizacao_tijolo,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsMemorizacaoTapete') AS dep_mms_memorizacao_tapete,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsLinguagemACaneca') AS dep_mms_linguagem_acaneca,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsLinguagemBFrase2') AS dep_mms_linguagem_bfrase2,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsEscolaridade2') AS dep_mms_escolaridade2,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depDesenhaRelogio1') AS dep_desenhar_elogio1,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depDesenhaRelogio2') AS dep_desenhar_elogio2,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depDesenhaRelogio3') AS dep_desenhar_elogio3,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenNutricaoPerdeuPeso') AS idoso_depen_nutricao_perdeu_peso,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenDificuldadeVisual') AS idoso_depen_dificuldade_visual,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenDificuldadeVisualOlhoDir') AS idoso_depen_dificuldade_visual_olho_dir,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenDificuldadeVisualOlhoEsq') AS idoso_depen_dificuldade_visual_olho_esq,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenTesteSussurro') AS idoso_depen_teste_sussurro,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenCerumeOd') AS idoso_depen_cerume_od,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenCerumeOe') AS idoso_depen_cerume_oe,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenPerdeUrina') AS idoso_depen_perde_urina,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenPerdeUrinaIncomodo') AS idoso_depen_perde_urina_incomodo,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenTristeFrequente') AS idoso_depen_triste_frequente,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenRepetirNomesObject') AS idoso_depen_repetir_nomes_object,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenTocarNumCamaos') AS idoso_depen_tocar_num_camaos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenApanharLapisMesa') AS idoso_depen_apanhar_lapis_mesa,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenLevantarDaCadeira') AS idoso_depen_levantar_da_cadeira,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenCapazCaminhar3m') AS idoso_depen_capaz_caminhar3m,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenVoltarSentar') AS idoso_depen_voltar_sentar,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenSairCama') AS idoso_depen_sair_cama,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenCapazVestir') AS idoso_depen_capaz_vestir,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenPrePreFeicoes') AS idoso_depen_pre_pre_feicoes,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenFazerCompras') AS idoso_depen_fazer_compras,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenHaEscadas') AS idoso_depen_ha_escadas,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenHaTapetesSoltos') AS idoso_depen_ha_tapetes_soltos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenHaCorrimaoBanh') AS idoso_depen_ha_corrimao_banh,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenQuedaQtd') AS idoso_depen_queda_qtd,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenAlgAjudaRincapc') AS idoso_depen_alg_ajudar_incapc,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenAlgAjudaRincapcQuem') AS idoso_depen_alg_ajudar_incapc_quem,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].idosodepenAlgAjudaRincapcQuemTomarDecis') AS idoso_depen_alg_ajudar_incapc_quem_tomar_decis,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].katzTomarBanho') AS katz_tomar_banho,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].katzVestirse') AS katz_vestirse,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].katzIrwc') AS katz_irwc,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].katzTransferencia') AS katz_transferencia,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].katzContinencia') AS katz_continencia,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].katzAlimentacao') AS katz_alimentacao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].katzClassificacao') AS katz_classificacao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer1') AS dep_questionario_pfeffer1,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer2') AS dep_questionario_pfeffer2,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer3') AS dep_questionario_pfeffer3,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer4') AS dep_questionario_pfeffer4,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer5') AS dep_questionario_pfeffer5,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer6') AS dep_questionario_pfeffer6,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer7') AS dep_questionario_pfeffer7,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer8') AS dep_questionario_pfeffer8,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer9') AS dep_questionario_pfeffer9,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer10') AS dep_questionario_pfeffer10,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfeffer11') AS dep_questionario_pfeffer11,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depQuestionarioPfefferPontos') AS dep_questionario_pfeffer_pontos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonUtilizarTelefone') AS lawton_utilizar_telefone,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonPlaneSpecial') AS lawton_plane_special,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonIrCompras') AS lawton_ir_compras,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonRefDiarias') AS lawton_ref_diarias,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonArruCasa') AS lawton_arru_casa,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonCuidCasa') AS lawton_cuid_casa,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonCuidRoupa') AS lawton_cuid_roupa,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonMedAdequadamente') AS lawton_med_adequadamente,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonGerirDinheiro') AS lawton_gerir_dinheiro,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].lawtonPontuacao') AS lawton_pontuacao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiEquilibrio') AS tinneti_equilibrio,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiLevantar') AS tinneti_levantar,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiLevantarTen') AS tinneti_levantar_ten,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiPosLevantar') AS tinneti_pos_levantar,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinneti3Campos') AS tinneti_3_campos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiOlhos') AS tinneti_olhos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiGirando360') AS tinneti_girando360,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiSentado') AS tinneti_sentado,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiIniMarcha') AS tinneti_ini_marcha,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiCompPassosd') AS tinneti_comp_passosd,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiCompPassose') AS tinneti_comp_passose,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiAltPassosd') AS tinneti_alt_passosd,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiAltPassose') AS tinneti_alt_passose,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiSimetria') AS tinneti_simetria,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiContinuidadePassos') AS tinneti_continuidade_passos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiDirecao') AS tinneti_direcao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiTronco') AS tinneti_tronco,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiTornozelos') AS tinneti_tornozelos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].tinnetiPontuacao') AS tinneti_pontuacao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginIdadeQualSuaIdade') AS ivcf20_plugin_idade_qual_sua_idade,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginAutopercepcaoSaudeVcdIriaDaSuaSaude') AS ivcf20_plugin_autopercepcao_saude_vcd_iria_da_sua_saude,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginAtividadesVidaDiariaDeixouFazerCompras') AS ivcf20_plugin_atividades_vida_diaria_deixou_fazer_compras,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginAtividadesVidaDiariaDeixouControlarDinheiro') AS ivcf20_plugin_atividades_vida_diaria_deixou_controlar_dinheiro,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginAtividadesVidaDiariaDeixouRealizarTrabalhos') AS ivcf20_plugin_atividades_vida_diaria_deixou_realizar_trabalhos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginAtividadesVidaDiariaDeixouTomarBanho') AS ivcf20_plugin_atividades_vida_diaria_deixou_tomar_banho,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginCognicaoFamiliarFalouFicandoEsquecido') AS ivcf20_plugin_cognicao_familiar_falou_ficando_esquecido,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginCognicaoEsquecimentoEstaPiorandoUltMeses') AS ivcf20_plugin_cognicao_esquecimento_esta_piorando_ult_meses,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginCognicaoEsquecimentoImpedindoAtividadeCotidiano') AS ivcf20_plugin_cognicao_esquecimento_impedindo_atividade_cotidiano,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginHumorUltMesDesanimo') AS ivcf20_plugin_humor_ult_mes_desanimo,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginHumorPerdeuInteresseAtividade') AS ivcf20_plugin_humor_perdeu_interesse_atividade,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginMobilidadeIncapazElevarBraco') AS ivcf20_plugin_mobilidade_incapaz_elevar_braco,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginMobilidadeIncapazSegurarPeqObjetos') AS ivcf20_plugin_mobilidade_incapaz_segurar_peq_objetos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginMobilidadeTemAlgumaQuatroCondicoes') AS ivcf20_plugin_mobilidade_tem_alguma_quatro_condicoes,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginMobilidadeDificuldadeCaminhar') AS ivcf20_plugin_mobilidade_dificuldade_caminhar,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginMobilidadeTeveDuasMaisQuedas') AS ivcf20_plugin_mobilidade_teve_duas_mais_quedas,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginMobilidadePerdeUrinaFezesSemQuerer') AS ivcf20_plugin_mobilidade_perde_urina_fezes_sem_querer,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginComunicacaoVisao') AS ivcf20_plugin_comunicacao_visao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginComunicacaoAudicao') AS ivcf20_plugin_comunicacao_audicao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginComorbidadesMultiplasTemAlgumaTresCondicoes') AS ivcf20_plugin_comorbidades_multiplas_tem_alguma_tres_condicoes,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginPontuacaoFinal') AS ivcf20_plugin_pontuacao_final,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ivcf20PluginCorrelacao') AS ivcf20_plugin_correlacao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginIdadeQualSuaIdade') AS ves13_plugin_idade_qual_sua_idade,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginAutopercepcaoSaudeVcdIriaDaSuaSaude') AS ves13_plugin_autopercepcao_saude_vcd_iria_da_sua_saude,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginLimitacaoFisicaCurvar') AS ves13_plugin_limitacao_fisica_curvar,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginLimitacaoFisicaLevantar') AS ves13_plugin_limitacao_fisica_levantar,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginLimitacaoFisicaElevar') AS ves13_plugin_limitacao_fisica_elevar,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginLimitacaoFisicaEscrever') AS ves13_plugin_limitacao_fisica_escrever,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginLimitacaoFisicaAndar') AS ves13_plugin_limitacao_fisica_andar,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginLimitacaoFisicaFazer') AS ves13_plugin_limitacao_fisica_fazer,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginIncapacidadesDeixouFazerCompras') AS ves13_plugin_incapacidades_deixou_fazer_compras,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginIncapacidadesDeixouControlarDinheiro') AS ves13_plugin_incapacidades_deixou_controlar_dinheiro,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginIncapacidadesDeixouCaminharCasa') AS ves13_plugin_incapacidades_deixou_caminhar_casa,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginIncapacidadesDeixouRealizarTrabalhos') AS ves13_plugin_incapacidades_deixou_realizar_trabalhos,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginIncapacidadesDeixouTomarBanho') AS ves13_plugin_incapacidades_deixou_tomar_banho,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginPontuacaoFinal') AS ves13_plugin_pontuacao_final,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginCorrelacao') AS ves13_plugin_correlacao,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].ves13PluginProvidencias') AS ves13_plugin_providencias,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculoO') AS dep_mms_calculo_o,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculoD') AS dep_mms_calculo_d,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculoN') AS dep_mms_calculo_n,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculoU') AS dep_mms_calculo_u,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].depMmsCalculoM') AS dep_mms_calculo_m,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].utResponsavel') AS ut_responsavel,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].utenteEscolaridadeResponsavel') AS utente_escolaridade_responsavel,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].utenteDataNascimentoResponsavel') AS utente_data_nascimento_responsavel,
    JSON_EXTRACT_SCALAR(json_data, '$.idoso[0].utenteGrauParentescoResponsavel') AS utente_grau_parentesco_responsavel,
    loaded_at,
    data_particao

  FROM bruto_atendimento
),

idoso_dedup AS (
  SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY id_prontuario_global ORDER BY loaded_at DESC) AS rn
  FROM idoso_extraido
)

SELECT * EXCEPT(rn)
FROM idoso_dedup
WHERE rn = 1