{% macro add_accents_bairros(bairro) %}
case
  when trim(upper({{bairro}})) in ("ABOLICAO", "ABOLIÇAO") then "Abolição"
  when trim(upper({{bairro}})) = "AGUA SANTA" then "Água Santa"
  when trim(upper({{bairro}})) = "ANDARAI" then "Andaraí"
  when trim(upper({{bairro}})) = "BANCARIOS" then "Bancários"
  when trim(upper({{bairro}})) in ("BRAZ DE PINA", "BRAS DE PINA") then "Brás de Pina"
  when trim(upper({{bairro}})) = "CIDADE UNIVERSITARIA" then "Cidade Universitária"
  when trim(upper({{bairro}})) = "COCOTA" then "Cocotá"
  when trim(upper({{bairro}})) = "COLEGIO" then "Colégio"
  when trim(upper({{bairro}})) = "COMPLEXO DO ALEMAO" then "Complexo do Alemão"
  when trim(upper({{bairro}})) = "ESTACIO" then "Estácio"
  when trim(upper({{bairro}})) = "GALEAO" then "Galeão"
  when trim(upper({{bairro}})) = "GARDENIA AZUL" then "Gardênia Azul"
  when trim(upper({{bairro}})) = "GAVEA" then "Gávea"
  when trim(upper({{bairro}})) = "GERINCINO" then "Gericinó"
  when trim(upper({{bairro}})) = "GLORIA" then "Glória"
  when trim(upper({{bairro}})) = "GRAJAU" then "Grajaú"
  when trim(upper({{bairro}})) = "HIGIENOPOLIS" then "Higienópolis"
  when trim(upper({{bairro}})) = "HONORIO GURGEL" then "Honório Gurgel"
  when trim(upper({{bairro}})) = "HUMAITA" then "Humaitá"
  when trim(upper({{bairro}})) = "INHAUMA" then "Inhaúma"
  when trim(upper({{bairro}})) = "INHOAIBA" then "Inhoaíba"
  when trim(upper({{bairro}})) = "IRAJA" then "Irajá"
  when trim(upper({{bairro}})) = "ITANHANGA" then "Itanhangá"
  when trim(upper({{bairro}})) = "JACARE" then "Jacaré"
  when trim(upper({{bairro}})) = "JACAREPAGUA" then "Jacarepaguá"
  when trim(upper({{bairro}})) = "JARDIM AMERICA" then "Jardim América"
  when trim(upper({{bairro}})) = "JARDIM BOTANICO" then "Jardim Botânico"
  when trim(upper({{bairro}})) = "JOA" then "Joá"
  when trim(upper({{bairro}})) = "MAGALHAES BASTOS" then "Magalhães Bastos"
  when trim(upper({{bairro}})) = "MACARANA" then "Maracanã"
  when trim(upper({{bairro}})) = "MARE" then "Maré"
  when trim(upper({{bairro}})) = "MARIA DA GRACA" then "Maria da Graça"
  when trim(upper({{bairro}})) = "MEIER" then "Méier"
  when trim(upper({{bairro}})) = "MONERO" then "Moneró"
  when trim(upper({{bairro}})) = "PACIENCIA" then "Paciência"
  when trim(upper({{bairro}})) = "PARQUETA" then "Paquetá"
  when trim(upper({{bairro}})) = "PARQUE COLUMBIA" then "Parque Colúmbia"
  when trim(upper({{bairro}})) = "SANTISSIMO" then "Santíssimo"
  when trim(upper({{bairro}})) = "SAO CONRADO" then "São Conrado"
  when trim(upper({{bairro}})) = "SAO CRISTOVAO" then "São Cristóvão"
  when trim(upper({{bairro}})) = "SAO FRANCISCO XAVIER" then "São Francisco Xavier"
  when trim(upper({{bairro}})) = "SAUDE" then "Saúde"
  when trim(upper({{bairro}})) = "SENADOR CAMARA" then "Senador Camará"
  when trim(upper({{bairro}})) = "TAUA" then "Tauá"
  when trim(upper({{bairro}})) = "TOMAS COELHO" then "Tomás Coelho"
  when trim(upper({{bairro}})) = "TURIACU" then "Turiaçu"
  else {{ proper_br(bairro) }}
end
{% endmacro %}
