{% macro proper_text(text) %}
CASE 
WHEN (REGEXP_INSTR( {{text}},'[a-z]')-1) < 0
THEN 
    CONCAT(
        UPPER(
            SUBSTR(
                {{text}},
                REGEXP_INSTR(
                    {{text}},
                    '[a-z]'
                ), 
                1
            )
        ),
        LOWER(
            SUBSTR(
                {{text}},
                REGEXP_INSTR(
                    {{text}},
                    '[a-z]'
                )+1, 
                length({{text}})
            )
        )
    )
ELSE
    CONCAT(
        SUBSTR(
            {{text}},
            0,
            REGEXP_INSTR(
                {{text}},
                '[a-z]'
            )-1
        ),
        UPPER(
            SUBSTR(
                {{text}},
                REGEXP_INSTR(
                    {{text}},
                    '[a-z]'
                ), 
                1
            )
        ),
        LOWER(
            SUBSTR(
                {{text}},
                REGEXP_INSTR(
                    {{text}},
                    '[a-z]'
                )+1, 
                length({{text}})
            )
        )
    )
END

{% endmacro %}