{% macro remove_invalid_email(texto) %}
        WHEN {{ texto }} IN ("NONE") THEN NULL
        WHEN REGEXP_CONTAINS(SPLIT({{ texto }}, '@')[OFFSET(0)], r'^(X+)$') THEN NULL   -- Remove valores com letras repeditas
        WHEN REGEXP_CONTAINS(SPLIT({{ texto }}, '@')[OFFSET(0)], r'^[A-Za-z]$') THEN NULL  -- Remove valores com apenas uma letra
        WHEN SPLIT({{ texto }}, '@')[OFFSET(0)] IN (
            "NAOTEM",
            "NAOPOSSUI",
            "NAOINFORMADO",
            "NAO",
            "N",
            "NAOTEMEMAIL",
            "SEMINFORMACAO",
            "SEM",
            "NAOPOSSUO",
            "NAOCONSTA",
            "SEMEMAIL",
            "NTEM",
            "SEMINF",
            "TESTE",
            "NAOSEAPLICA",
            "IGNORADO",
            "NAOSEI",
            "NT",
            "EMAIL",
            "NP",
            "XXX.XXX",
            "NAOINFORMOU",
            "NENHUM",
            "SEMINFO",
            "NAOTENHO",
            "NAOTEM.NAOTEM",
            "NPOSSUI",
            "NAOPOSSUIEMAIL",
            "NAO.NAO",
            "NOT",
            "ND",
            "NINFORMADO",
            "NAOPOSSUICFZA",
            "NAOINFO",
            "GMAIL",
            "NAOPOSSUE",
            "NAODECLARADO",
            "NAOTEMIMAIL",
            "NOTEM",
            "NAOINF",
            "SEM.INFORMACAO",
            "NAOUSA",
            "EMAILNAOINFORMADO",
            "NAO.TEM",
            "SEMINFORMACOES",
            "TESTE.TESTE",
            "NOEMAIL",
            "NOATEM",
            "SEMINFOR",
            "NAO.TEM23",
            "NAOINFORMA",
            "NAOTE",
            "NAOPOSSUIIMAIL",
            "XXX.XX"
        ) THEN NULL
{% endmacro %}
