{{
    config(
        alias="repec__atendimentos_clinicos_acs",
        materialized="table",
        tags=["subpav", "repec"]
    )
}}

with
    source as (
        select *
        from {{ source("brutos_plataforma_subpav_staging", "subpav_repec__atendimentos_clinicos_acs") }}
    ),

    tratar_campos as (
        select
            {{ process_null('id_atendimento_acs') }} as id_atendimento_acs,
            {{ process_null('cnes_entidade') }} as cnes_entidade,
            {{ process_null('id_paciente') }} as id_paciente,
            {{ process_null('id_profissional') }} as id_profissional,
            {{ process_null('id_agendamento') }} as id_agendamento,
            {{ process_null('data_atendimento_acs') }} as data_atendimento_acs,
            {{ process_null('data_registro') }} as data_registro,
            {{ process_null('fuma') }} as fuma,
            {{ process_null('diab_referido_paciente') }} as diab_referido_paciente,
            {{ process_null('hta_referido_paciente') }} as hta_referido_paciente,
            {{ process_null('tab_referido_paciente') }} as tab_referido_paciente,
            {{ process_null('doencas_cond_referidas') }} as doencas_cond_referidas,
            {{ process_null('doencas_cond_resolv') }} as doencas_cond_resolv,
            {{ process_null('kits_odonto_entregues') }} as kits_odonto_entregues,
            {{ process_null('gestante_idadeaberturafichab') }} as gestante_idadeaberturafichab,
            {{ process_null('gestante_idadeencerramentofichab') }} as gestante_idadeencerramentofichab,
            {{ process_null('gestante_dataaberturafichab') }} as gestante_dataaberturafichab,
            {{ process_null('gestante_dataencerramentofichab') }} as gestante_dataencerramentofichab,
            {{ process_null('gestante_visitoumaternidadereferencia') }} as gestante_visitoumaternidadereferencia,
            {{ process_null('gestante_maternidadereferencia') }} as gestante_maternidadereferencia,
            {{ process_null('gestante_dtaultimaregra') }} as gestante_dtaultimaregra,
            {{ process_null('gestante_dpp') }} as gestante_dpp,
            {{ process_null('gestante_informgestacao_fatoresrisco') }} as gestante_informgestacao_fatoresrisco,
            {{ process_null('gestante_informgestacao_hiv') }} as gestante_informgestacao_hiv,
            {{ process_null('gestante_informgestacao_iniciotrat_hiv') }} as gestante_informgestacao_iniciotrat_hiv,
            {{ process_null('gestante_informgestacao_parceirotrat_hiv') }} as gestante_informgestacao_parceirotrat_hiv,
            {{ process_null('gestante_sifilis') }} as gestante_sifilis,
            {{ process_null('gestante_informgestacao_iniciotrat_sifilis') }} as gestante_informgestacao_iniciotrat_sifilis,
            {{ process_null('gestante_informgestacao_toxoplasmose') }} as gestante_informgestacao_toxoplasmose,
            {{ process_null('gestante__iniciotrat_toxoplasmose') }} as gestante__iniciotrat_toxoplasmose,
            {{ process_null('gestante_informgestacao_resultgestactual') }} as gestante_informgestacao_resultgestactual,
            {{ process_null('gestante_result_gest_actual_num_fetos') }} as gestante_result_gest_actual_num_fetos,
            {{ process_null('gestante_meses_1mes_dtavisitaacs') }} as gestante_meses_1mes_dtavisitaacs,
            {{ process_null('gestante_meses_1mes_dtaconsprenatal_plg') }} as gestante_meses_1mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_1mes_vacinasemdia') }} as gestante_meses_1mes_vacinasemdia,
            {{ process_null('gestante_meses_1mes_pressaoalta') }} as gestante_meses_1mes_pressaoalta,
            {{ process_null('gestante_meses_1mes_sangramentovag') }} as gestante_meses_1mes_sangramentovag,
            {{ process_null('gestante_meses_1mes_dorcontracao') }} as gestante_meses_1mes_dorcontracao,
            {{ process_null('gestante_meses_1mes_estadonutricion') }} as gestante_meses_1mes_estadonutricion,
            {{ process_null('gestante_meses_1mes_tratodontolog') }} as gestante_meses_1mes_tratodontolog,
            {{ process_null('gestante_meses_1mes_apoiofamiliar') }} as gestante_meses_1mes_apoiofamiliar,
            {{ process_null('gestante_meses_1mes_paienvolvido') }} as gestante_meses_1mes_paienvolvido,
            {{ process_null('gestante_meses_2mes_dtavisitaacs') }} as gestante_meses_2mes_dtavisitaacs,
            {{ process_null('gestante_meses_2mes_dtaconsprenatal_plg') }} as gestante_meses_2mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_2mes_vacinasemdia') }} as gestante_meses_2mes_vacinasemdia,
            {{ process_null('gestante_meses_2mes_pressaoalta') }} as gestante_meses_2mes_pressaoalta,
            {{ process_null('gestante_meses_2mes_sangramentovag') }} as gestante_meses_2mes_sangramentovag,
            {{ process_null('gestante_meses_2mes_dorcontracao') }} as gestante_meses_2mes_dorcontracao,
            {{ process_null('gestante_meses_2mes_estadonutricion') }} as gestante_meses_2mes_estadonutricion,
            {{ process_null('gestante_meses_2mes_tratodontolog') }} as gestante_meses_2mes_tratodontolog,
            {{ process_null('gestante_meses_2mes_apoiofamiliar') }} as gestante_meses_2mes_apoiofamiliar,
            {{ process_null('gestante_meses_2mes_paienvolvido') }} as gestante_meses_2mes_paienvolvido,
            {{ process_null('gestante_meses_3mes_dtavisitaacs') }} as gestante_meses_3mes_dtavisitaacs,
            {{ process_null('gestante_meses_3mes_dtaconsprenatal_plg') }} as gestante_meses_3mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_3mes_vacinasemdia') }} as gestante_meses_3mes_vacinasemdia,
            {{ process_null('gestante_meses_3mes_pressaoalta') }} as gestante_meses_3mes_pressaoalta,
            {{ process_null('gestante_meses_3mes_sangramentovag') }} as gestante_meses_3mes_sangramentovag,
            {{ process_null('gestante_meses_3mes_dorcontracao') }} as gestante_meses_3mes_dorcontracao,
            {{ process_null('gestante_meses_3mes_estadonutricion') }} as gestante_meses_3mes_estadonutricion,
            {{ process_null('gestante_meses_3mes_tratodontolog') }} as gestante_meses_3mes_tratodontolog,
            {{ process_null('gestante_meses_3mes_apoiofamiliar') }} as gestante_meses_3mes_apoiofamiliar,
            {{ process_null('gestante_meses_3mes_paienvolvido') }} as gestante_meses_3mes_paienvolvido,
            {{ process_null('gestante_meses_4mes_dtavisitaacs') }} as gestante_meses_4mes_dtavisitaacs,
            {{ process_null('gestante_meses_4mes_dtaconsprenatal_plg') }} as gestante_meses_4mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_4mes_vacinasemdia') }} as gestante_meses_4mes_vacinasemdia,
            {{ process_null('gestante_meses_4mes_pressaoalta') }} as gestante_meses_4mes_pressaoalta,
            {{ process_null('gestante_meses_4mes_sangramentovag') }} as gestante_meses_4mes_sangramentovag,
            {{ process_null('gestante_meses_4mes_dorcontracao') }} as gestante_meses_4mes_dorcontracao,
            {{ process_null('gestante_meses_4mes_estadonutricion') }} as gestante_meses_4mes_estadonutricion,
            {{ process_null('gestante_meses_4mes_tratodontolog') }} as gestante_meses_4mes_tratodontolog,
            {{ process_null('gestante_meses_4mes_apoiofamiliar') }} as gestante_meses_4mes_apoiofamiliar,
            {{ process_null('gestante_meses_4mes_paienvolvido') }} as gestante_meses_4mes_paienvolvido,
            {{ process_null('gestante_meses_5mes_dtavisitaacs') }} as gestante_meses_5mes_dtavisitaacs,
            {{ process_null('gestante_meses_5mes_dtaconsprenatal_plg') }} as gestante_meses_5mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_5mes_vacinasemdia') }} as gestante_meses_5mes_vacinasemdia,
            {{ process_null('gestante_meses_5mes_pressaoalta') }} as gestante_meses_5mes_pressaoalta,
            {{ process_null('gestante_meses_5mes_sangramentovag') }} as gestante_meses_5mes_sangramentovag,
            {{ process_null('gestante_meses_5mes_dorcontracao') }} as gestante_meses_5mes_dorcontracao,
            {{ process_null('gestante_meses_5mes_estadonutricion') }} as gestante_meses_5mes_estadonutricion,
            {{ process_null('gestante_meses_5mes_tratodontolog') }} as gestante_meses_5mes_tratodontolog,
            {{ process_null('gestante_meses_5mes_apoiofamiliar') }} as gestante_meses_5mes_apoiofamiliar,
            {{ process_null('gestante_meses_5mes_paienvolvido') }} as gestante_meses_5mes_paienvolvido,
            {{ process_null('gestante_meses_6mes_dtavisitaacs') }} as gestante_meses_6mes_dtavisitaacs,
            {{ process_null('gestante_meses_6mes_dtaconsprenatal_plg') }} as gestante_meses_6mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_6mes_vacinasemdia') }} as gestante_meses_6mes_vacinasemdia,
            {{ process_null('gestante_meses_6mes_pressaoalta') }} as gestante_meses_6mes_pressaoalta,
            {{ process_null('gestante_meses_6mes_sangramentovag') }} as gestante_meses_6mes_sangramentovag,
            {{ process_null('gestante_meses_6mes_dorcontracao') }} as gestante_meses_6mes_dorcontracao,
            {{ process_null('gestante_meses_6mes_estadonutricion') }} as gestante_meses_6mes_estadonutricion,
            {{ process_null('gestante_meses_6mes_tratodontolog') }} as gestante_meses_6mes_tratodontolog,
            {{ process_null('gestante_meses_6mes_apoiofamiliar') }} as gestante_meses_6mes_apoiofamiliar,
            {{ process_null('gestante_meses_6mes_paienvolvido') }} as gestante_meses_6mes_paienvolvido,
            {{ process_null('gestante_meses_7mes_dtavisitaacs') }} as gestante_meses_7mes_dtavisitaacs,
            {{ process_null('gestante_meses_7mes_dtaconsprenatal_plg') }} as gestante_meses_7mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_7mes_vacinasemdia') }} as gestante_meses_7mes_vacinasemdia,
            {{ process_null('gestante_meses_7mes_pressaoalta') }} as gestante_meses_7mes_pressaoalta,
            {{ process_null('gestante_meses_7mes_sangramentovag') }} as gestante_meses_7mes_sangramentovag,
            {{ process_null('gestante_meses_7mes_dorcontracao') }} as gestante_meses_7mes_dorcontracao,
            {{ process_null('gestante_meses_7mes_estadonutricion') }} as gestante_meses_7mes_estadonutricion,
            {{ process_null('gestante_meses_7mes_tratodontolog') }} as gestante_meses_7mes_tratodontolog,
            {{ process_null('gestante_meses_7mes_apoiofamiliar') }} as gestante_meses_7mes_apoiofamiliar,
            {{ process_null('gestante_meses_7mes_paienvolvido') }} as gestante_meses_7mes_paienvolvido,
            {{ process_null('gestante_meses_8mes_dtavisitaacs') }} as gestante_meses_8mes_dtavisitaacs,
            {{ process_null('gestante_meses_8mes_dtaconsprenatal_plg') }} as gestante_meses_8mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_8mes_vacinasemdia') }} as gestante_meses_8mes_vacinasemdia,
            {{ process_null('gestante_meses_8mes_pressaoalta') }} as gestante_meses_8mes_pressaoalta,
            {{ process_null('gestante_meses_8mes_sangramentovag') }} as gestante_meses_8mes_sangramentovag,
            {{ process_null('gestante_meses_8mes_dorcontracao') }} as gestante_meses_8mes_dorcontracao,
            {{ process_null('gestante_meses_8mes_estadonutricion') }} as gestante_meses_8mes_estadonutricion,
            {{ process_null('gestante_meses_8mes_tratodontolog') }} as gestante_meses_8mes_tratodontolog,
            {{ process_null('gestante_meses_8mes_apoiofamiliar') }} as gestante_meses_8mes_apoiofamiliar,
            {{ process_null('gestante_meses_8mes_paienvolvido') }} as gestante_meses_8mes_paienvolvido,
            {{ process_null('gestante_meses_9mes_dtavisitaacs') }} as gestante_meses_9mes_dtavisitaacs,
            {{ process_null('gestante_meses_9mes_dtaconsprenatal_plg') }} as gestante_meses_9mes_dtaconsprenatal_plg,
            {{ process_null('gestante_meses_9mes_vacinasemdia') }} as gestante_meses_9mes_vacinasemdia,
            {{ process_null('gestante_meses_9mes_pressaoalta') }} as gestante_meses_9mes_pressaoalta,
            {{ process_null('gestante_meses_9mes_sangramentovag') }} as gestante_meses_9mes_sangramentovag,
            {{ process_null('gestante_meses_9mes_dorcontracao') }} as gestante_meses_9mes_dorcontracao,
            {{ process_null('gestante_meses_9mes_estadonutricion') }} as gestante_meses_9mes_estadonutricion,
            {{ process_null('gestante_meses_9mes_tratodontolog') }} as gestante_meses_9mes_tratodontolog,
            {{ process_null('gestante_meses_9mes_apoiofamiliar') }} as gestante_meses_9mes_apoiofamiliar,
            {{ process_null('gestante_meses_9mes_paienvolvido') }} as gestante_meses_9mes_paienvolvido,
            {{ process_null('gestante_observacoes') }} as gestante_observacoes,
            {{ process_null('diab_idadeaberturafichab') }} as diab_idadeaberturafichab,
            {{ process_null('diab_idadeencerramentofichab') }} as diab_idadeencerramentofichab,
            {{ process_null('diab_dataaberturafichab') }} as diab_dataaberturafichab,
            {{ process_null('diab_dataencerramentofichab') }} as diab_dataencerramentofichab,
            {{ process_null('diab_hipertenso') }} as diab_hipertenso,
            {{ process_null('diab_fumante') }} as diab_fumante,
            {{ process_null('diab_eacompanoutrolocal') }} as diab_eacompanoutrolocal,
            {{ process_null('diab_obeso') }} as diab_obeso,
            {{ process_null('diab_fazdieta') }} as diab_fazdieta,
            {{ process_null('diab_fazexerciciofis') }} as diab_fazexerciciofis,
            {{ process_null('diab_feridape') }} as diab_feridape,
            {{ process_null('diab_usainsulina') }} as diab_usainsulina,
            {{ process_null('diab_hipogliceoral') }} as diab_hipogliceoral,
            {{ process_null('diab_tratodontologico') }} as diab_tratodontologico,
            {{ process_null('diab_diaultimaconsulta') }} as diab_diaultimaconsulta,
            {{ process_null('diab_diaproximaconsulta') }} as diab_diaproximaconsulta,
            {{ process_null('diab_ocorrencias') }} as diab_ocorrencias,
            {{ process_null('hta_idadeaberturafichab') }} as hta_idadeaberturafichab,
            {{ process_null('hta_idadeencerramentofichab') }} as hta_idadeencerramentofichab,
            {{ process_null('hta_dataaberturafichab') }} as hta_dataaberturafichab,
            {{ process_null('hta_dataencerramentofichab') }} as hta_dataencerramentofichab,
            {{ process_null('hta_diabetico') }} as hta_diabetico,
            {{ process_null('hta_fumante') }} as hta_fumante,
            {{ process_null('hta_eacompanoutrolocal') }} as hta_eacompanoutrolocal,
            {{ process_null('hta_toma_med') }} as hta_toma_med,
            {{ process_null('hta_fazdieta') }} as hta_fazdieta,
            {{ process_null('hta_fazexerciciofis') }} as hta_fazexerciciofis,
            {{ process_null('hta_press_art_sis') }} as hta_press_art_sis,
            {{ process_null('hta_press_art_dis') }} as hta_press_art_dis,
            {{ process_null('hta_diaultimaconsulta') }} as hta_diaultimaconsulta,
            {{ process_null('hta_diaproximaconsulta') }} as hta_diaproximaconsulta,
            {{ process_null('hta_ocorrencias') }} as hta_ocorrencias,
            {{ process_null('tuber_idadeaberturafichab') }} as tuber_idadeaberturafichab,
            {{ process_null('tuber_idadeencerramentofichab') }} as tuber_idadeencerramentofichab,
            {{ process_null('tuber_dataaberturafichab') }} as tuber_dataaberturafichab,
            {{ process_null('tuber_dataencerramentofichab') }} as tuber_dataencerramentofichab,
            {{ process_null('tuber_diavisita') }} as tuber_diavisita,
            {{ process_null('tuber_diaultimaconsulta') }} as tuber_diaultimaconsulta,
            {{ process_null('tuber_diaproxconsulta') }} as tuber_diaproxconsulta,
            {{ process_null('tuber_tomamedic') }} as tuber_tomamedic,
            {{ process_null('tuber_tratsuperv') }} as tuber_tratsuperv,
            {{ process_null('tuber_reacindj') }} as tuber_reacindj,
            {{ process_null('tuber_exameescarro') }} as tuber_exameescarro,
            {{ process_null('tuber_numcontac') }} as tuber_numcontac,
            {{ process_null('tuber_comunicantes_referidos') }} as tuber_comunicantes_referidos,
            {{ process_null('tuber_contacmenos5anos') }} as tuber_contacmenos5anos,
            {{ process_null('tuber_menores5bcg') }} as tuber_menores5bcg,
            {{ process_null('tuber_contactexam') }} as tuber_contactexam,
            {{ process_null('tuber_historantcidadao') }} as tuber_historantcidadao,
            {{ process_null('tuber_historantcontac') }} as tuber_historantcontac,
            {{ process_null('hansen_idadeaberturafichab') }} as hansen_idadeaberturafichab,
            {{ process_null('hansen_idadeencerramentofichab') }} as hansen_idadeencerramentofichab,
            {{ process_null('hansen_dataaberturafichab') }} as hansen_dataaberturafichab,
            {{ process_null('hansen_dataencerramentofichab') }} as hansen_dataencerramentofichab,
            {{ process_null('hansen_diavisita') }} as hansen_diavisita,
            {{ process_null('hansen_diaultimaconsulta') }} as hansen_diaultimaconsulta,
            {{ process_null('hansen_diaproxconsulta') }} as hansen_diaproxconsulta,
            {{ process_null('hansen_tomamedic') }} as hansen_tomamedic,
            {{ process_null('hansen_dtaultimadosesuper') }} as hansen_dtaultimadosesuper,
            {{ process_null('hansen_autocuidado') }} as hansen_autocuidado,
            {{ process_null('hansen_numcontactos') }} as hansen_numcontactos,
            {{ process_null('hansen_comunicantes_referidos') }} as hansen_comunicantes_referidos,
            {{ process_null('hansen_ctsexaminados') }} as hansen_ctsexaminados,
            {{ process_null('hansen_receberambcg') }} as hansen_receberambcg,
            {{ process_null('crianca_nascimento_local') }} as crianca_nascimento_local,
            trim({{ remove_decode_chars_error("cast(" ~ process_null('crianca_nascimento_tipoparto') ~ " as string)") }}) as crianca_nascimento_tipoparto,
            {{ process_null('crianca_nascimento_peso') }} as crianca_nascimento_peso,
            {{ process_null('crianca_nascimento_indiceapgar5minuto') }} as crianca_nascimento_indiceapgar5minuto,
            {{ process_null('crianca_nascimento_dtatestepezinho') }} as crianca_nascimento_dtatestepezinho,
            {{ process_null('crianca_nascimento_obs') }} as crianca_nascimento_obs,
            {{ process_null('crianca_visitamensal_peso') }} as crianca_visitamensal_peso,
            {{ process_null('crianca_nascimento_comprimento') }} as crianca_nascimento_comprimento,
            {{ process_null('crianca_nascimento_perimetrocefalico') }} as crianca_nascimento_perimetrocefalico,
            trim({{ remove_decode_chars_error("cast(" ~ process_null('crianca_visitamensal_tipoaleitamento') ~ " as string)") }}) as crianca_visitamensal_tipoaleitamento,
            {{ process_null('crianca_visitamensal_vacinasemdia') }} as crianca_visitamensal_vacinasemdia,
            {{ process_null('crianca_visitamensal_estado_nutricional') }} as crianca_visitamensal_estado_nutricional,
            {{ process_null('crianca_visitamensal_atrasodesenvolvimento') }} as crianca_visitamensal_atrasodesenvolvimento,
            {{ process_null('crianca_visitamensal_diarreia') }} as crianca_visitamensal_diarreia,
            {{ process_null('crianca_visitamensal_infecagudarespiratoria') }} as crianca_visitamensal_infecagudarespiratoria,
            {{ process_null('crianca_visitamensal_obs') }} as crianca_visitamensal_obs,
            {{ process_null('deficiencia_deficiencia') }} as deficiencia_deficiencia,
            {{ process_null('deficiencia_ap_ajuda') }} as deficiencia_ap_ajuda,
            {{ process_null('deficiencia_forma_adq') }} as deficiencia_forma_adq,
            {{ process_null('deficiencia_faz_tratamento') }} as deficiencia_faz_tratamento,
            {{ process_null('deficiencia_tratamento') }} as deficiencia_tratamento,
            {{ process_null('deficiencia_tratamento_outros') }} as deficiencia_tratamento_outros,
            {{ process_null('deficiencia_atendimento_proposto') }} as deficiencia_atendimento_proposto,
            {{ process_null('deficiencia_local_tratamento') }} as deficiencia_local_tratamento,
            {{ process_null('deficiencia_avaliacao_tratamento') }} as deficiencia_avaliacao_tratamento,
            {{ process_null('deficiencia_avsoc') }} as deficiencia_avsoc,
            {{ process_null('deficiencia_obs') }} as deficiencia_obs,
            {{ process_null('origem_arquivo') }} as origem_arquivo,
            {{ process_null('origem_banco') }} as origem_banco,
            {{ repec_origem_unidade_para_cnes("origem_unidade") }} as cnes_origem,
            safe_cast({{ process_null('datalake_loaded_at') }} as timestamp) as datalake_loaded_at
        from source
    ),

    deduplicar as (
        select *
        from tratar_campos
        qualify row_number() over (
            partition by
                    id_atendimento_acs,
                    cnes_entidade,
                    id_paciente,
                    id_profissional,
                    id_agendamento,
                    data_atendimento_acs,
                    data_registro,
                    cnes_origem
            order by
                    datalake_loaded_at desc,
                    origem_arquivo desc
        ) = 1
    )

select *
from deduplicar
