{{
    config(
        alias        = "tb_investiga",
        materialized = "table",
        tags         = ["subpav", "sinanrio", "tb_investiga"]
    )
}}

with novo as (

    select
        nu_notificacao,
        dt_notificacao,
        co_cid,
        co_municipio_notificacao,
        nu_prontuario,
        tp_entrada,
        tp_institucionalizado,
        tp_raio_x,
        tp_turberculinico,
        tp_forma,
        tp_extrapulmonar_1,
        tp_extrapulmonar_2,
        ds_extrapulmonar_outro,
        st_agravo_aids,
        st_agravo_alcolismo,
        st_agravo_diabete,
        st_agravo_mental,
        st_agravo_outro,
        ds_agravo_outro,
        st_baciloscopia_escarro,
        st_baciloscopia_outro,
        st_baciloscopia_escarro2,
        tp_cultura_escarro,
        tp_cultura_outro,
        tp_hiv,
        tp_histopatologia,
        dt_inicio_tratamento,
        st_droga_rifampicina,
        st_droga_isoniazida,
        st_droga_etambutol,
        st_droga_estreptomicina,
        st_droga_pirazinamida,
        st_droga_etionamida,
        st_droga_outro,
        ds_droga_outro,
        tp_tratamento,
        nu_contato,
        co_uf_atual,
        co_municipio_atual,
        nu_notificacao_atual,
        dt_notificacao_atual,
        co_unidade_saude_atual,
        st_baciloscopia_2_mes,
        st_baciloscopia_4_mes,
        st_baciloscopia_6_mes,
        st_baciloscopia_1_mes,
        st_baciloscopia_3_mes,
        st_baciloscopia_5_mes,
        tp_tratamento_acompanhamento,
        dt_mudanca_tratamento,
        nu_contato_examinado,
        tp_situacao_mes_9,
        tp_situacao_mes_12,
        tp_situacao_encerramento,
        co_uf_residencia_atual,
        co_municipio_residencia_atual,
        nu_cep_residencia_atual,
        co_distrito_residencia_atual,
        co_bairro_residencia_atual,
        no_bairro_residencia_atual,
        dt_encerramento,
        tp_pcr_escarro,
        tp_pop_liberdade,
        tp_pop_rua,
        tp_pop_saude,
        tp_pop_imigrante,
        tp_benef_gov,
        st_agravo_drogas,
        st_agravo_tabaco,
        tp_molecular,
        tp_sensibilidade,
        nu_contato_identificados,
        tp_antirretroviral_trat,
        st_bacil_apos_6_mes,
        nu_prontuario_atual,
        tp_transf,
        co_uf_transf,
        co_municipio_transf,
        datalake_loaded_at

    from {{ ref("raw_plataforma_subpav_sinanrio__tb_investiga") }}

),

legado as (

    select
        l.nu_notificacao,
        l.dt_notificacao,
        l.co_cid,
        l.co_municipio_notificacao,
        l.nu_prontuario,
        l.tp_entrada,
        l.tp_institucionalizado,
        l.tp_raio_x,
        l.tp_turberculinico,
        l.tp_forma,
        l.tp_extrapulmonar_1,
        l.tp_extrapulmonar_2,
        l.ds_extrapulmonar_outro,
        l.st_agravo_aids,
        l.st_agravo_alcolismo,
        l.st_agravo_diabete,
        l.st_agravo_mental,
        l.st_agravo_outro,
        l.ds_agravo_outro,
        l.st_baciloscopia_escarro,
        l.st_baciloscopia_outro,
        l.st_baciloscopia_escarro2,
        l.tp_cultura_escarro,
        l.tp_cultura_outro,
        l.tp_hiv,
        l.tp_histopatologia,
        l.dt_inicio_tratamento,
        l.st_droga_rifampicina,
        l.st_droga_isoniazida,
        l.st_droga_etambutol,
        l.st_droga_estreptomicina,
        l.st_droga_pirazinamida,
        l.st_droga_etionamida,
        l.st_droga_outro,
        l.ds_droga_outro,
        l.tp_tratamento,
        l.nu_contato,
        l.co_uf_atual,
        l.co_municipio_atual,
        l.nu_notificacao_atual,
        l.dt_notificacao_atual,
        l.co_unidade_saude_atual,
        l.st_baciloscopia_2_mes,
        l.st_baciloscopia_4_mes,
        l.st_baciloscopia_6_mes,
        l.st_baciloscopia_1_mes,
        l.st_baciloscopia_3_mes,
        l.st_baciloscopia_5_mes,
        l.tp_tratamento_acompanhamento,
        l.dt_mudanca_tratamento,
        l.nu_contato_examinado,
        l.tp_situacao_mes_9,
        l.tp_situacao_mes_12,
        l.tp_situacao_encerramento,
        l.co_uf_residencia_atual,
        l.co_municipio_residencia_atual,
        l.nu_cep_residencia_atual,
        l.co_distrito_residencia_atual,
        l.co_bairro_residencia_atual,
        l.no_bairro_residencia_atual,
        l.dt_encerramento,
        l.tp_pcr_escarro,
        l.tp_pop_liberdade,
        l.tp_pop_rua,
        l.tp_pop_saude,
        l.tp_pop_imigrante,
        l.tp_benef_gov,
        l.st_agravo_drogas,
        l.st_agravo_tabaco,
        l.tp_molecular,
        l.tp_sensibilidade,
        l.nu_contato_identificados,
        l.tp_antirretroviral_trat,
        l.st_bacil_apos_6_mes,
        l.nu_prontuario_atual,
        l.tp_transf,
        l.co_uf_transf,
        l.co_municipio_transf,
        l.datalake_loaded_at

    from {{ ref("raw_plataforma_subpav_sinanrio_legado__tb_investiga") }} l
),

unionizado as (
    select * from novo
    union all
    select * from legado
)

select *
from unionizado
