{{ config(
    alias        = "notificacao",
    materialized = "table",
    tags         = ["subpav","sinanrio"],
    cluster_by   = ["nu_notificacao","dt_notificacao","co_cid","co_municipio_notificacao"]
) }}

with
    novo as (
        select
            'novo' as sistema_origem,
            nu_notificacao,
            dt_notificacao,
            co_cid,
            co_municipio_notificacao,
            co_unidade_notificacao,
            co_uf_notificacao,
            tp_notificacao,
            dt_diagnostico_sintoma,
            no_nome_paciente,
            dt_nascimento,
            nu_idade,
            tp_sexo,
            tp_gestante,
            tp_raca_cor,
            tp_escolaridade,
            nu_cartao_sus,
            no_nome_mae,
            co_uf_residencia,
            co_municipio_residencia,
            co_distrito_residencia,
            co_bairro_residencia,
            no_bairro_residencia,
            nu_cep_residencia,
            co_geo_campo_1,
            co_geo_campo_2,
            co_logradouro_residencia,
            no_logradouro_residencia,
            nu_residencia,
            ds_complemento_residencia,
            ds_referencia_residencia,
            nu_ddd_residencia,
            nu_telefone_residencia,
            tp_zona_residencia,
            co_pais_residencia,
            dt_investigacao,
            co_cbo_ocupacao,
            tp_classificacao_final,
            ds_classificacao_final,
            tp_criterio_confirmacao,
            tp_modo_infeccao,
            ds_modo_infeccao_outro,
            tp_local_infeccao,
            ds_local_infeccao_outro,
            tp_autoctone_residencia,
            co_uf_infeccao,
            co_pais_infeccao,
            co_municipio_infeccao,
            co_distrito_infeccao,
            co_bairro_infeccao,
            no_bairro_infeccao,
            co_unidade_infeccao,
            no_localidade_infeccao,
            st_doenca_trabalho,
            tp_evolucao_caso,
            ds_evolucao_caso_outro,
            dt_obito,
            dt_encerramento,
            ds_semana_notificacao,
            ds_semana_sintoma,
            ds_chave_fonetica,
            ds_soundex,
            dt_digitacao,
            dt_transf_us,
            dt_transf_dm,
            dt_transf_sm,
            dt_transf_rm,
            dt_transf_rs,
            dt_transf_se,
            nu_lote_vertical,
            nu_lote_horizontal,
            tp_duplicidade,
            tp_suspeita,
            st_vincula,
            tp_fluxo_retorno,
            st_modo_transmissao,
            tp_veiculo_transmissao,
            ds_veiculo_transmissao_outro,
            tp_local_surto,
            ds_local_outro,
            nu_caso_suspeito,
            tp_inquerito,
            nu_caso_examinado,
            nu_caso_positivo,
            ds_observacao,
            tp_delimitacao_surto,
            ds_delimitacao_surto_outro,
            st_fluxo_retorno_recebido,
            ds_identificador_registro,
            st_importado,
            st_criptografia,
            tp_sistema,
            st_espelho,
            ts_codigo1,
            ts_codigo2,
            tp_unidad_notificadora_externa,
            co_unidad_notificadora_externa,
            cpf_notificante,
            cpf_paciente,
            dnv_paciente,
            justificativa_cpf,
            lat,
            long,
            notif_assistente,
            resp_encerramento,
            st_agravo_tabagismo,
            st_pcr_escarro,
            tp_cultura_justificativa,
            visivel,
            finalizado,
            timestamp,
            datalake_loaded_at
        from {{ ref("raw_plataforma_subpav_sinanrio__notificacao") }}
    ),

    legado as (
        select
            'legado' as sistema_origem,
            l.nu_notificacao,
            l.dt_notificacao,
            l.co_cid,
            l.co_municipio_notificacao,
            l.co_unidade_notificacao,
            l.co_uf_notificacao,
            l.tp_notificacao,
            l.dt_diagnostico_sintoma,
            l.no_nome_paciente,
            l.dt_nascimento,
            l.nu_idade,
            l.tp_sexo,
            l.tp_gestante,
            l.tp_raca_cor,
            l.tp_escolaridade,
            l.nu_cartao_sus,
            l.no_nome_mae,
            l.co_uf_residencia,
            l.co_municipio_residencia,
            l.co_distrito_residencia,
            l.co_bairro_residencia,
            l.no_bairro_residencia,
            l.nu_cep_residencia,
            l.co_geo_campo_1,
            l.co_geo_campo_2,
            l.co_logradouro_residencia,
            l.no_logradouro_residencia,
            l.nu_residencia,
            l.ds_complemento_residencia,
            l.ds_referencia_residencia,
            l.nu_ddd_residencia,
            l.nu_telefone_residencia,
            l.tp_zona_residencia,
            l.co_pais_residencia,
            l.dt_investigacao,
            l.co_cbo_ocupacao,
            l.tp_classificacao_final,
            l.ds_classificacao_final,
            l.tp_criterio_confirmacao,
            l.tp_modo_infeccao,
            l.ds_modo_infeccao_outro,
            l.tp_local_infeccao,
            l.ds_local_infeccao_outro,
            l.tp_autoctone_residencia,
            l.co_uf_infeccao,
            l.co_pais_infeccao,
            l.co_municipio_infeccao,
            l.co_distrito_infeccao,
            l.co_bairro_infeccao,
            l.no_bairro_infeccao,
            l.co_unidade_infeccao,
            l.no_localidade_infeccao,
            l.st_doenca_trabalho,
            l.tp_evolucao_caso,
            l.ds_evolucao_caso_outro,
            l.dt_obito,
            l.dt_encerramento,
            l.ds_semana_notificacao,
            l.ds_semana_sintoma,
            l.ds_chave_fonetica,
            l.ds_soundex,
            l.dt_digitacao,
            l.dt_transf_us,
            l.dt_transf_dm,
            l.dt_transf_sm,
            l.dt_transf_rm,
            l.dt_transf_rs,
            l.dt_transf_se,
            l.nu_lote_vertical,
            l.nu_lote_horizontal,
            l.tp_duplicidade,
            l.tp_suspeita,
            l.st_vincula,
            l.tp_fluxo_retorno,
            l.st_modo_transmissao,
            l.tp_veiculo_transmissao,
            l.ds_veiculo_transmissao_outro,
            l.tp_local_surto,
            l.ds_local_outro,
            l.nu_caso_suspeito,
            l.tp_inquerito,
            l.nu_caso_examinado,
            l.nu_caso_positivo,
            l.ds_observacao,
            l.tp_delimitacao_surto,
            l.ds_delimitacao_surto_outro,
            l.st_fluxo_retorno_recebido,
            l.ds_identificador_registro,
            l.st_importado,
            l.st_criptografia,
            l.tp_sistema,
            l.st_espelho,
            l.ts_codigo1,
            l.ts_codigo2,
            l.tp_unidad_notificadora_externa,
            l.co_unidad_notificadora_externa,
            l.cpf_notificante,
            l.cpf_paciente,
            l.dnv_paciente,
            l.justificativa as justificativa_cpf,
            l.lat,
            l.long,
            l.notif_assistente,
            l.resp_encerramento,
            l.st_agravo_tabagismo,
            l.st_pcr_escarro,
            l.tp_cultura_justificativa,
            l.visivel,
            l.finalizado,
            l.timestamp,
            l.datalake_loaded_at
        from {{ ref("raw_plataforma_subpav_sinanrio_legado__notificacao") }} as l
    ),

    conciliado as (
        select
            *,
            row_number() over (
                partition by nu_notificacao, dt_notificacao, co_cid, co_municipio_notificacao
                order by
                    case when sistema_origem = 'novo' then 1 else 2 end,
                    coalesce(timestamp, datalake_loaded_at) desc
            ) as rn
        from (
            select * from novo
            union all
            select * from legado
        )
    )

select
    *
from conciliado
where rn = 1
